import {test} from 'node:test';import assert from 'node:assert/strict';
import {EventStore} from '../src/core/store.ts';import {projectAgentModels,agentSelection,AGENT_MODEL_SUBJECT} from '../src/adapters/agent-models.ts';import {consultAgents,projectAgents} from '../src/adapters/agent-consultation.ts';
import type {ContextFrame} from '../src/core/loop.ts';
const frame:ContextFrame={goal:'goal',history:[],directives:[],evidence:[],capabilities:[],model:'coordinator',step:0};
test('owner route replay composes defaults/roles/reset and refuses model-authored or secret-bearing preferences',()=>{
 const log=new EventStore('routes',Date.now);const choose=(role:string,selection:any)=>log.append({kind:'note',subject:AGENT_MODEL_SUBJECT,data:{version:1,author:'human',role,selection}});
 choose('*',{provider:'opencode',model:'free/default'});choose('review',{provider:'opencode',model:'free/review'});assert.equal(agentSelection(projectAgentModels(log.toSession().events),'review')?.model,'free/review');choose('review',null);assert.equal(agentSelection(projectAgentModels(log.toSession().events),'review')?.model,'free/default');choose('*',null);assert.equal(agentSelection(projectAgentModels(log.toSession().events),'review'),null);const before=log.revision;projectAgentModels(log.toSession().events);assert.equal(log.revision,before);
 for(const data of [{version:1,author:'model',role:'review',selection:null},{version:2,author:'human',role:'review',selection:null},{version:1,author:'human',role:'review',selection:{provider:'opencode',apiKey:'fixture-secret'}}]){const bad=new EventStore('bad',Date.now);bad.append({kind:'note',subject:AGENT_MODEL_SUBJECT,data});assert.throws(()=>projectAgentModels(bad.toSession().events));}
});
test('parallel consultants use distinct owner adapters; payload models cannot authorize a provider',async()=>{
 const log=new EventStore('agents',Date.now);const calls:string[]=[];const result=await consultAgents({input:{tasks:[{role:'review',task:'review',model:'paid/hostile'},{role:'research',task:'research',provider:'paid'}]},model:{name:'unused',async infer(){throw Error('wrong model');}},route:role=>({label:'free/'+role,adapter:{name:role,async infer(){calls.push(role);return {text:role+' finding',toolCalls:[]};}}}),frame,signal:new AbortController().signal,current:()=>true,append:e=>log.append(e),execution:'e',modelLabel:'unused',notice:()=>{}});
 assert.equal(result.exit,0);assert.deepEqual(calls.sort(),['research','review']);assert.deepEqual(projectAgents(log.toSession().events).map(a=>a.model).sort(),['free/research','free/review']);
});
test('unavailable role refuses before any admission/inference instead of provider fallback',async()=>{
 const log=new EventStore('agents',Date.now);let calls=0;const result=await consultAgents({input:{tasks:[{role:'review',task:'t'},{role:'research',task:'t'}]},model:{name:'fallback',async infer(){calls++;return {text:'x',toolCalls:[]};}},route:role=>{if(role==='research')throw Error('unavailable');return {adapter:{name:'valid',async infer(){calls++;return {text:'x',toolCalls:[]};}},label:'valid'};},frame,signal:new AbortController().signal,current:()=>true,append:e=>log.append(e),execution:'e',modelLabel:'fallback',notice:()=>{}});assert.equal(result.exit,126);assert.equal(calls,0);assert.equal(log.revision,-1);
});
test('human model override preserves coordinator and invalidates a pending consultation',async()=>{
 const {createProducer}=await import('../apps/terminal/src/producer/index.ts');const {createStore}=await import('../apps/terminal/src/app/store.ts');const view=createStore();let release!:()=>void;const wait=new Promise<void>(r=>release=r);let started!:()=>void;const ready=new Promise<void>(r=>started=r);let steps=0;const coordinator={name:'coordinateur',async infer(){return {text:'',toolCalls:++steps===1?[{name:'consult_agents',input:{tasks:[{role:'review',task:'Review'}]}}]:[]};}};
 const producer=createProducer({cwd:'/fixture/project',identities:[],store:view,maxSlices:1,model:coordinator,tools:{async run(){throw Error('no tools');}},agentModel:selection=>({label:selection.model!,adapter:{name:selection.model!,async infer(){started();await wait;return {text:'old model answer',toolCalls:[]};}}})});
 assert.deepEqual(producer.selectAgentModel!('review',{provider:'opencode',model:'free/one'}),{ok:true});producer.say('qzfixture');await ready;assert.deepEqual(producer.selectAgentModel!('review',{provider:'opencode',model:'free/two'}),{ok:true});release();const end=Date.now()+3000;while(view.get().busy&&Date.now()<end)await new Promise(r=>setTimeout(r,5));assert.equal(view.get().busy,false);assert.match(producer.agentPage!().lines.join('\n'),/stale context/);assert.doesNotMatch(producer.agentPage!().lines.join('\n'),/old model answer/);assert.equal(coordinator.name,'coordinateur');assert.equal(producer.agentModelTargets!().find(t=>t.role==='review')!.selection!.model,'free/two');
});
test('owner routes survive actual session close/reopen without writing on inspection',async()=>{
 const {mkdtempSync,rmSync}=await import('node:fs');const {join}=await import('node:path');const {tmpdir}=await import('node:os');const {TerminalSession}=await import('../src/adapters/terminal-session.ts');const {createProducer}=await import('../apps/terminal/src/producer/index.ts');const {createStore}=await import('../apps/terminal/src/app/store.ts');const root=mkdtempSync(join(tmpdir(),'cs-agent-route-reload-'));
 const fixture=(journal:any)=>createProducer({journal,cwd:root,identities:[],store:createStore(),model:{name:'coordinator',async infer(){throw Error('inspection must not infer');}},tools:{async run(){throw Error('no effects');}},agentModel:s=>({label:s.model!,adapter:{name:s.model!,async infer(){throw Error('inspection');}}})});let first:any,second:any;
 try{first=new TerminalSession({root:join(root,'sessions'),cwd:root});assert.deepEqual(fixture(first).selectAgentModel!('review',{provider:'opencode',model:'free/review',apiKey:'fixture-secret'} as any),{ok:true});const id=first.metadata.id;assert.doesNotMatch(JSON.stringify(first.core.toSession()),/fixture-secret/);first.close();second=new TerminalSession({root:join(root,'sessions'),cwd:root,id});const before=second.core.revision;assert.equal(fixture(second).agentModelTargets!().find(t=>t.role==='review')!.selection!.model,'free/review');assert.equal(second.core.revision,before);
 }finally{first?.close();second?.close();rmSync(root,{recursive:true,force:true});}
});
test('real binary transports receive distinct explicitly selected model IDs',async()=>{
 const {mkdtempSync,writeFileSync,chmodSync,rmSync}=await import('node:fs');const {join}=await import('node:path');const {tmpdir}=await import('node:os');const {resolveModel}=await import('../src/adapters/default-model.ts');const root=mkdtempSync(join(tmpdir(),'cs-agent-multi-model-'));const binary=join(root,'provider');
 try{writeFileSync(binary,`#!${process.execPath}\nconst argv=process.argv.slice(2);const model=argv[argv.indexOf('--model')+1];if(!argv.includes('--pure')||!model)process.exit(1);console.log(JSON.stringify({type:'text',part:{type:'text',text:JSON.stringify({text:model,toolCalls:[]})}}));`);chmodSync(binary,0o700);const log=new EventStore('models',Date.now);
 const result=await consultAgents({input:{tasks:[{role:'research',task:'t'},{role:'review',task:'t'}]},model:{name:'wrong',async infer(){throw Error('no fallback');}},route:role=>{const selected=resolveModel({project:root,provider:'opencode',model:'fixture/'+role,preferences:{},env:{CUESHEET_OPENCODE_BIN:binary}});if('missing' in selected)throw Error(selected.missing);return {adapter:selected.adapter,label:selected.model!};},frame,signal:new AbortController().signal,current:()=>true,append:e=>log.append(e),execution:'e',modelLabel:'wrong',notice:()=>{}});assert.equal(result.exit,0,result.output);assert.deepEqual(projectAgents(log.toSession().events).map(a=>a.text).sort(),['fixture/research','fixture/review']);
 }finally{rmSync(root,{recursive:true,force:true});}
});
