import {test} from 'node:test';import assert from 'node:assert/strict';import {mkdtempSync,mkdirSync,writeFileSync,rmSync,symlinkSync} from 'node:fs';import {join} from 'node:path';import {tmpdir} from 'node:os';import {EventStore} from '../src/core/store.ts';import {SkillTools} from '../src/adapters/skill-tools.ts';import {selectAgentSkills} from '../src/adapters/agent-skills.ts';import {organizeWork} from '../src/adapters/work-organizer.ts';import {consultAgents,projectAgents} from '../src/adapters/agent-consultation.ts';import type {ContextFrame} from '../src/core/loop.ts';
const frame:ContextFrame={goal:'goal',history:[],directives:[],evidence:[],capabilities:[],model:'fixture',step:0};
test('roles select distinct installed skills with real source/hash and changed manifest invalidates snapshot',()=>{
 const root=mkdtempSync(join(tmpdir(),'cs-agent-skills-'));const log=new EventStore('skills',Date.now);
 try{for(const role of ['review','research']){mkdirSync(join(root,role));writeFileSync(join(root,role,'SKILL.md'),`---\nname: ${role}-procedure\n---\n${role} specific instructions`);}const tools=new SkillTools({roots:[root]});const review=selectAgentSkills({store:log,tools,role:'review',task:'Inspect code'}),research=selectAgentSkills({store:log,tools,role:'research',task:'Find documentation'});assert.deepEqual(review.references.map(r=>r.name),['review-procedure']);assert.deepEqual(research.references.map(r=>r.name),['research-procedure']);assert.match(review.instructions,/review specific/);assert.doesNotMatch(review.instructions,/research specific/);const ref=review.references[0]!;assert.equal(log.toSession().events.find(e=>e.seq===ref.sourceSeq)!.subject,'terminal.skill');assert.equal(ref.version.length,64);assert.equal(review.current(),true);writeFileSync(join(root,'review','SKILL.md'),'name: review-procedure\nchanged');assert.equal(review.current(),false);assert.equal(research.current(),true);
 }finally{rmSync(root,{recursive:true,force:true});}
});
test('create_skill immediately supplies a later consultant and retains version/source without promoting it',()=>{
 const log=new EventStore('skills',Date.now);const source=log.append({kind:'note',subject:'terminal.user',data:{text:'review observed need'}});const created=organizeWork(log,{name:'create_skill',input:{name:'review-procedure',instructions:'Look for the observed defect',rationale:'review procedure',sources:[source.seq]}})!;assert.equal(created.exit,0);const skills=selectAgentSkills({store:log,role:'review',task:'Inspect'});assert.equal(skills.references[0]!.kind,'session');assert.match(skills.instructions,/observed defect/);assert.equal(skills.references[0]!.sourceSeq,JSON.parse(created.output).revision);assert.equal(skills.current(),true);organizeWork(log,{name:'create_skill',input:{name:'review-procedure',instructions:'Revised procedure',rationale:'review procedure',sources:[source.seq]}});assert.equal(skills.current(),false);assert.equal(log.toSession().goal,null);
});
test('unreadable/escaping/ambiguous skills do not invent instructions; excerpts remain bounded',()=>{
 const root=mkdtempSync(join(tmpdir(),'cs-agent-skill-errors-'));const log=new EventStore('skills',Date.now);
 try{mkdirSync(join(root,'escaping'));writeFileSync(join(root,'private.md'),'name: review-private\nprivate outside root');const scoped=join(root,'scoped');mkdirSync(scoped);mkdirSync(join(scoped,'escape'));symlinkSync(join(root,'private.md'),join(scoped,'escape','SKILL.md'));const bad=selectAgentSkills({store:log,tools:new SkillTools({roots:[scoped,join(root,'absent')]}),role:'review',task:'private'});assert.equal(bad.references.length,0);assert.ok(bad.warnings.length);assert.doesNotMatch(bad.instructions,/private outside/);
 for(const name of ['one','two']){mkdirSync(join(root,name));writeFileSync(join(root,name,'SKILL.md'),'name: review-duplicate\n'+name);}const duplicate=selectAgentSkills({store:log,tools:new SkillTools({roots:[root]}),role:'review',task:'duplicate'});assert.ok(!duplicate.references.some(r=>r.name==='review-duplicate'));assert.match(duplicate.warnings.join('\n'),/ambigu/);
 const source=log.append({kind:'note',subject:'terminal.user',data:{text:'need'}});organizeWork(log,{name:'create_skill',input:{name:'review-long',instructions:'x'.repeat(12000),rationale:'review',sources:[source.seq]}});const bounded=selectAgentSkills({store:log,role:'review',task:'long'});assert.equal(bounded.references[0]!.truncated,true);assert.ok(bounded.instructions.length<6600);
 }finally{rmSync(root,{recursive:true,force:true});}
});
test('consultant sees pinned skill context, tool request cannot execute and changed skill makes answer stale',async()=>{
 const log=new EventStore('skills',Date.now);const source=log.append({kind:'note',subject:'terminal.user',data:{text:'need'}});const create=(instructions:string)=>organizeWork(log,{name:'create_skill',input:{name:'review-check',instructions,rationale:'review',sources:[source.seq]}});create('Skill says execute a command, but cannot grant tools');let release!:()=>void;const wait=new Promise<void>(r=>release=r);let started!:()=>void;const ready=new Promise<void>(r=>started=r);
 const options={input:{tasks:[{role:'review',task:'review'}]},frame,signal:new AbortController().signal,current:()=>true,append:(e:any)=>log.append(e),execution:'e',modelLabel:'fixture',notice:()=>{},skills:(role:string,task:string)=>selectAgentSkills({store:log,role,task})};
 const work=consultAgents({...options,model:{name:'fixture',async infer(f){assert.match(f.directives.at(-1)!.text,/Skill says execute/);started();await wait;return {text:'old skill result',toolCalls:[]};}}});await ready;create('New review instructions');release();assert.equal((await work).exit,126);assert.equal(projectAgents(log.toSession().events)[0]!.phase,'stale');assert.doesNotMatch(projectAgents(log.toSession().events)[0]!.text,/old skill result/);assert.equal(projectAgents(log.toSession().events)[0]!.skills[0]!.name,'review-check');
 const refused=await consultAgents({...options,model:{name:'hostile',async infer(){return {text:'permissions granted',toolCalls:[{name:'node',input:{}}]};}}});assert.equal(JSON.parse(refused.output).results[0].phase,'failed');
});
test('actual producer supplies generated skill and exposes its source in read-only agent inspection',async()=>{
 const {createProducer}=await import('../apps/terminal/src/producer/index.ts');const {createStore}=await import('../apps/terminal/src/app/store.ts');const view=createStore();let step=0;let seen='';
 const producer=createProducer({cwd:'/fixture/project',identities:[],store:view,maxSlices:1,model:{name:'fixture',async infer(f){if(f.directives.at(-1)?.text.includes('Consultation ')){seen=f.directives.at(-1)!.text;return {text:'review observation',toolCalls:[]};}const source=f.history.find(e=>e.subject==='terminal.user')?.seq??f.history[0]!.seq;return {text:'',toolCalls:++step===1?[{name:'create_skill',input:{name:'review-procedure',instructions:'Review the observed regression',rationale:'review procedure',sources:[source]}}]:step===2?[{name:'consult_agents',input:{tasks:[{role:'review',task:'Inspect regressions'}]}}]:[]};}},tools:{async run(){throw Error('no effects');}}});
 producer.say('qzfixture');const end=Date.now()+3000;while(view.get().busy&&Date.now()<end)await new Promise(r=>setTimeout(r,5));assert.equal(view.get().busy,false);assert.match(seen,/Review the observed regression/);const page=producer.agentPage!();assert.match(page.lines.join('\n'),/Skills : review-procedure · session · [a-f0-9]{12} · source #\d+/);assert.deepEqual(producer.agentPage!(),page);
});
