import {test} from 'node:test';import assert from 'node:assert/strict';import {mkdtempSync,writeFileSync,rmSync} from 'node:fs';import {join,resolve} from 'node:path';import {tmpdir} from 'node:os';import {spawnSync} from 'node:child_process';import {childEnv} from './fixtures/hermetic-env.ts';
test('real palette opens live agents, refreshes, scrolls and resizes without touching composer',()=>{
 const root=mkdtempSync(join(tmpdir(),'cs-agent-ui-'));const terminal=resolve('apps/terminal');
 try{const script=join(root,'ui.tsx');writeFileSync(join(root,'package.json'),'{"type":"module"}');
 writeFileSync(script,`import React from ${JSON.stringify(join(terminal,'node_modules/react/index.js'))};import {render} from ${JSON.stringify(join(terminal,'node_modules/ink/build/index.js'))};import {App} from ${JSON.stringify(join(terminal,'src/app/App.tsx'))};import {createStore} from ${JSON.stringify(join(terminal,'src/app/store.ts'))};import {PassThrough} from 'node:stream';
const store=createStore();store.send({type:'compose',text:'correction retained'});let phase='en cours',calls=0;const producer={say(){throw Error('must not submit')},choose(){},agentPage(){calls++;return {digest:'1',offset:0,nextOffset:null,lines:['review · '+phase,'Model: fixture-model','Skills : review-procedure · source #42','Workspace: '+('/long-workspace-segment'.repeat(24)), 'Diagnostic: invalid tool batch; no call executed',...Array.from({length:20},(_,i)=>'finding '+i)]}}};
const out=new PassThrough();Object.assign(out,{columns:80,rows:24,isTTY:false});let last='',frames=[];out.on('data',b=>{last=b.toString();frames.push(last)});const input=new PassThrough();Object.assign(input,{isTTY:true,setRawMode(){},ref(){},unref(){}});const app=render(<App store={store} producer={producer}/>,{stdout:out,stderr:out,stdin:input,debug:true,exitOnCtrlC:false});const tick=()=>new Promise(r=>setTimeout(r,45));const until=async(p)=>{const end=Date.now()+4000;while(!p()&&Date.now()<end)await tick();if(!p())throw Error('missing UI state '+last)};
await tick();input.write('\\x0b');await until(()=>last.includes('Commands'));input.write('Agents');await tick();input.write('\\r');await until(()=>last.includes('review · en cours'));phase='proposition reçue';await until(()=>last.includes('proposition reçue'));const sizes=[];for(const [columns,rows] of [[80,24],[120,30],[160,50],[240,70]]){out.columns=columns;out.rows=rows;out.emit('resize');await tick();sizes.push({rows,frame:last});}for(let i=0;i<60;i++){input.write('\\x1b[B');await tick();}input.write('\\x1b');await tick();const closed=store.get().overlay==='none',composer=store.get().composer;app.unmount();console.log(JSON.stringify({sizes,closed,composer,calls,frames:frames.join('\\n')}));`);
 const run=spawnSync(process.execPath,[join(terminal,'node_modules/tsx/dist/cli.mjs'),script],{encoding:'utf8',timeout:15000,env:childEnv(root)});assert.equal(run.status,0,run.stderr);const result=JSON.parse(run.stdout.trim());assert.equal(result.closed,true);assert.equal(result.composer,'correction retained');assert.ok(result.calls>=2);assert.match(result.frames,/finding 19/);assert.match(result.frames,/Diagnostic: invalid tool batch/);assert.match(result.frames,/review-procedure · source #42/);for(const s of result.sizes){assert.match(s.frame,/Agents/);assert.match(s.frame,/Esc close/);assert.match(s.frame,/correction retained/);assert.ok(s.frame.split('\n').length<=s.rows,s.frame);}
 }finally{rmSync(root,{recursive:true,force:true});}
});
