import { describe, it } from "node:test";
import assert from "node:assert/strict";

import {
  buildSnapshotFrontier,
  renderFrontier,
  snapshotPortfolio,
} from "../src/adapters/frontier.ts";
import type { DurableObject } from "../src/core/memory.ts";

const obj = (over: Partial<DurableObject> = {}): DurableObject => ({
  id: "o1",
  kind: "FutureTrigger",
  horizon: "sleep",
  what: "a runtime is justified",
  why: "ADR-001 forbids it until measured",
  evidence: [{ source: "bench", observed: "0 observed", at: "2026-09-29" }],
  status: "active",
  related_to: [],
  ...over,
});

describe("snapshotPortfolio", () => {
  it("reads the real portfolio and separates writable from held", () => {
    const s = snapshotPortfolio();
    assert.ok(s.projects.length > 0, "the registry must yield projects");
    assert.ok(
      s.free.length + s.held.length === s.projects.length,
      "every repository is either free or held, never neither",
    );
  });

  it("holds a repository with uncommitted work, and says which", () => {
    const s = snapshotPortfolio();
    // The state of the world changes; the invariant does not. A repo with
    // dirty files must never appear in the free list.
    for (const p of s.projects) {
      if (p.dirty > 0) {
        assert.ok(s.held.includes(p.entry.name), `${p.entry.name} has ${p.dirty} dirty files`);
        assert.ok(!s.free.includes(p.entry.name));
      }
    }
  });
});

describe("buildSnapshotFrontier", () => {
  it("reports an unevaluable condition instead of quietly not waking it", () => {
    const objects = [
      obj({
        id: "F-runtime",
        revisit_when: {
          signal: "three alignment failures",
          requires: ">= 3 reproducible failures",
          satisfiedBy: ["alignment_failures", "no_existing_primitive"],
          matched: true,
        },
      }),
    ];

    const { frontier, unevaluable } = buildSnapshotFrontier({
      objects,
      measured: { alignment_failures: 4 },
    });

    assert.equal(frontier.woken.length, 0, "a missing measurement cannot wake anything");
    assert.equal(unevaluable.length, 1);
    assert.match(unevaluable[0].why, /no_existing_primitive/);
  });

  it("wakes only when the condition is both evaluable and matched", () => {
    const objects = [
      obj({
        id: "F-wakes",
        revisit_when: {
          signal: "s",
          requires: "r",
          satisfiedBy: ["m"],
          matched: true,
        },
      }),
    ];
    const { frontier } = buildSnapshotFrontier({ objects, measured: { m: 1 } });
    assert.equal(frontier.woken.length, 1);
  });
});

describe("renderFrontier", () => {
  it("is a session-sized document, not the research corpus", () => {
    const objects = [
      obj({ id: "n1", horizon: "now", what: "own the state" }),
      obj({ id: "w1", horizon: "watch", what: "measured evolution", revisit_when: {
        signal: "s", requires: "repeated procedures", satisfiedBy: ["procedures"], matched: false } }),
    ];
    const { frontier, snapshot, unevaluable } = buildSnapshotFrontier({
      objects,
      measured: {},
    });
    const md = renderFrontier(frontier, snapshot, unevaluable, frontier.woken);

    assert.ok(md.length < 8000, `frontier must stay small, got ${md.length} bytes`);
    assert.match(md, /GENERATED by/);
    assert.match(md, /Do not edit by hand/);
  });

  it("states plainly that an unevaluable condition is not a verdict", () => {
    const objects = [
      obj({ id: "u1", revisit_when: {
        signal: "s", requires: "r", satisfiedBy: ["missing_measure"], matched: true } }),
    ];
    const { frontier, snapshot, unevaluable } = buildSnapshotFrontier({
      objects,
      measured: {},
    });
    const md = renderFrontier(frontier, snapshot, unevaluable, frontier.woken);

    assert.match(md, /could not be evaluated/);
    assert.match(md, /not a met condition/);
  });

  it("prints a falsified belief, its counterexample and its replacement", () => {
    const dead: DurableObject = {
      ...obj({ id: "F2", what: "hash alone suffices" }),
      status: "falsified",
      original_belief: "unchanged content does not invalidate dependants",
      counterexample: "world-kernel 15/16",
      replacement: "hash plus deriver policy identity",
    };
    const { frontier, snapshot, unevaluable } = buildSnapshotFrontier({
      objects: [dead],
      measured: {},
    });
    const md = renderFrontier(frontier, snapshot, unevaluable, frontier.woken);

    assert.match(md, /unchanged content does not invalidate dependants/);
    assert.match(md, /world-kernel 15\/16/);
    assert.match(md, /hash plus deriver policy identity/);
  });
});
