import {test} from 'node:test';import assert from 'node:assert/strict';import {mkdtempSync,writeFileSync,rmSync} from 'node:fs';import {join,resolve} from 'node:path';import {tmpdir} from 'node:os';import {spawnSync} from 'node:child_process';import {childEnv} from './fixtures/hermetic-env.ts';
test('work inspection follows identity, scrolls results, opens actions and preserves correction',()=>{
 const root=mkdtempSync(join(tmpdir(),'cs-work-ui-')),terminal=resolve('apps/terminal');
 try{
 writeFileSync(join(root,'package.json'),'{"type":"module"}');
 const script=join(root,'ui.tsx');writeFileSync(script,`
import React from ${JSON.stringify(join(terminal,'node_modules/react/index.js'))};import {render} from ${JSON.stringify(join(terminal,'node_modules/ink/build/index.js'))};import {App} from ${JSON.stringify(join(terminal,'src/app/App.tsx'))};import {createStore} from ${JSON.stringify(join(terminal,'src/app/store.ts'))};import {PassThrough} from 'node:stream';
const store=createStore();store.send({type:'submit',text:'Make restart reliable'});store.send({type:'began'});store.send({type:'compose',text:'preserved correction'});store.send({type:'reasoning',text:'PRIVATE_REASONING_MUST_NOT_RENDER',kind:'reasoning'});store.send({type:'observed',entries:[{id:'action42',kind:'action',label:'Read contract',detail:'contract.ts',certainty:'confirmed'}]});
let workers=[{id:'review',label:'A7',role:'review',task:'Check restart receipts',phase:'active',model:'fixture-route',source:42,result:'',helping:'coordinator',routeReason:'Inherited session model'}];let effects=0;
const producer={say(){effects++},choose(){},workSurface(){return {intent:'Make restart reliable',corrections:[],tasks:[],workers}},sharedContextPage(){return {digest:'1',offset:0,nextOffset:null,lines:['SOURCE_CONTEXT_42']}}};
const out=new PassThrough();Object.assign(out,{columns:80,rows:24,isTTY:false});let frame='',frames=[];out.on('data',b=>{frame=b.toString();frames.push(frame)});const input=new PassThrough();Object.assign(input,{isTTY:true,setRawMode(){},ref(){},unref(){}});const app=render(<App store={store} producer={producer}/>,{stdout:out,stderr:out,stdin:input,debug:true,exitOnCtrlC:false});const tick=()=>new Promise(r=>setTimeout(r,70));
await tick();const initial=frame;input.write('\\t');await tick();const opened=frame;input.write('\\r');await tick();const detail=frame;
workers=[{id:'other',label:'A8',role:'other',task:'NEW_WORKER',phase:'active',model:'other-route',source:44,result:''},{...workers[0],phase:'result',result:Array.from({length:35},(_,i)=>'RESULT_'+i).join('\\n')}];store.send({type:'logged',line:'result recorded'});await tick();const updated=frame;input.write('\\x1b[6~');await tick();input.write('\\x1b[6~');await tick();input.write('\\x1b[6~');await tick();const scrolled=frame;
const sizes=[];input.write('\\r');await tick();for(const [columns,rows] of [[80,24],[120,30],[160,50],[240,70]]){out.columns=columns;out.rows=rows;out.emit('resize');await tick();sizes.push({rows,frame});}
input.write('c');await tick();const context=frame;input.write('\\x1b');await tick();const closed=store.get().overlay, draft=store.get().composer;
const returned=frame;input.write('r');await tick();input.write('\\t');await tick();input.write('d');await tick();const changes=store.get().overlay;input.write('\\x1b');await tick();input.write('r');await tick();const before=store.get().composer;input.write('!');await tick();const after=store.get().composer;input.write('\\t');await tick();workers=[];store.send({type:'logged',line:'scope replaced'});await tick();input.write('\\r');await tick();const stale=frame;app.unmount();console.log(JSON.stringify({initial,opened,detail,updated,scrolled,sizes,context,returned,closed,draft,changes,before,after,stale,effects}));`);
 const run=spawnSync(process.execPath,[join(terminal,'node_modules/tsx/dist/cli.mjs'),script],{encoding:'utf8',timeout:15000,env:childEnv(root)});assert.equal(run.status,0,run.stderr);const r=JSON.parse(run.stdout.trim());
 assert.doesNotMatch(r.initial,/PRIVATE_REASONING/);assert.match(r.initial,/Tab inspect/);assert.match(r.opened,/Check restart receipts/);assert.match(r.detail,/fixture-route/);assert.match(r.detail,/Inherited session model/);assert.match(r.initial,/helping main task/);assert.match(r.detail,/Journal source #42/);assert.match(r.updated,/proposal · unverified/);assert.match(r.updated,/Check restart receipts/);assert.doesNotMatch(r.updated,/other-route/);assert.match(r.scrolled,/RESULT_3[0-4]/);assert.match(r.context,/SOURCE_CONTEXT_42/);assert.equal(r.closed,'work');assert.match(r.returned,/Check restart receipts/);assert.equal(r.draft,'preserved correction');assert.equal(r.changes,'changes');assert.equal(r.after,r.before+'!');assert.equal(r.effects,0);assert.match(r.stale,/No longer current/);assert.match(r.stale,/Check restart receipts/);
 for(const s of r.sizes){assert.match(s.frame,/Check restart receipts/);assert.match(s.frame,/preserved correction/);assert.match(s.frame,/Enter detail/);assert.ok(s.frame.trimEnd().split('\n').length<=s.rows,s.frame);}
 }finally{rmSync(root,{recursive:true,force:true});}
});
test('history anchor survives inspection while new results arrive',()=>{
 const root=mkdtempSync(join(tmpdir(),'cs-work-anchor-')),terminal=resolve('apps/terminal');try{
 writeFileSync(join(root,'package.json'),'{"type":"module"}');const script=join(root,'anchor.tsx');writeFileSync(script,`
import React from ${JSON.stringify(join(terminal,'node_modules/react/index.js'))};import {render} from ${JSON.stringify(join(terminal,'node_modules/ink/build/index.js'))};import {App} from ${JSON.stringify(join(terminal,'src/app/App.tsx'))};import {createStore} from ${JSON.stringify(join(terminal,'src/app/store.ts'))};import {PassThrough} from 'node:stream';
const store=createStore();store.send({type:'observed',entries:Array.from({length:35},(_,i)=>({id:'item'+i,kind:'cuesheet',text:'HISTORY_'+String(i).padStart(2,'0')}))});store.send({type:'compose',text:'my draft'});const out=new PassThrough();Object.assign(out,{columns:80,rows:24,isTTY:false});let frame='';out.on('data',b=>frame=b.toString());const input=new PassThrough();Object.assign(input,{isTTY:true,setRawMode(){},ref(){},unref(){}});const app=render(<App store={store} producer={{say(){},choose(){}}}/>,{stdout:out,stderr:out,stdin:input,debug:true,exitOnCtrlC:false});const tick=()=>new Promise(r=>setTimeout(r,80));await tick();input.write('\\x1b[5~');await tick();const before=frame;input.write('\\t');await tick();store.send({type:'observed',entries:[{id:'late',kind:'cuesheet',text:'NEW_HIDDEN_RESULT'}]});await tick();input.write('\\x1b[6~');await tick();input.write('\\x1b');await tick();const after=frame;app.unmount();console.log(JSON.stringify({before,after}));`);
 const run=spawnSync(process.execPath,[join(terminal,'node_modules/tsx/dist/cli.mjs'),script],{encoding:'utf8',timeout:10000,env:childEnv(root)});assert.equal(run.status,0,run.stderr);const r=JSON.parse(run.stdout.trim());const marks=(s:string)=>s.match(/HISTORY_\d+/g);assert.ok(marks(r.before)?.length);assert.deepEqual(marks(r.after),marks(r.before));assert.doesNotMatch(r.after,/NEW_HIDDEN_RESULT/);assert.match(r.after,/my draft/);
 }finally{rmSync(root,{recursive:true,force:true});}
});
