import {test} from 'node:test';import assert from 'node:assert/strict';import {mkdtempSync,writeFileSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join,resolve} from 'node:path';import {spawnSync} from 'node:child_process';
test('long live reasoning preserves intent and composer at four sizes, and inspection scrolls',()=>{
 const root=mkdtempSync(join(tmpdir(),'cs-live-layout-'));try{const terminal=resolve('apps/terminal');const script=join(root,'render.tsx');writeFileSync(join(root,'package.json'),'{"type":"module"}');writeFileSync(script,`
 import React from ${JSON.stringify(join(terminal,'node_modules/react/index.js'))};import {render,Box,Text} from ${JSON.stringify(join(terminal,'node_modules/ink/build/index.js'))};import {Timeline} from ${JSON.stringify(join(terminal,'src/components/Timeline.tsx'))};import {Inspect} from ${JSON.stringify(join(terminal,'src/overlays/Inspect.tsx'))};import {PassThrough} from 'node:stream';
 const pause=()=>new Promise(r=>setTimeout(r,40)),reasoning=Array.from({length:100},(_,i)=>'STEP_'+String(i).padStart(3,'0')+' Published Unicode 🙂').join('\\n');const results=[];
 for(const [columns,rows] of [[80,24],[120,30],[160,50],[240,70]]){const out=new PassThrough();Object.assign(out,{columns,rows,isTTY:false});let last='';out.on('data',b=>last=b.toString());const input=new PassThrough();Object.assign(input,{isTTY:true,setRawMode(){},ref(){},unref(){}});const app=render(<Box height={rows-1} flexDirection="column"><Timeline width={Math.min(96,columns-4)} rows={rows-8} visible={rows-8} context={['  └─ A7 · Review receipts · running']} busy reasoning={reasoning} entries={[{id:'human',kind:'you',text:'KEEP_INTENT visible while working'},{id:'a',kind:'action',label:'Read',detail:'contract.ts',certainty:'confirmed'},{id:'b',kind:'action',label:'Verify',detail:'compatibility',certainty:'active'}]}/><Text>KEEP_COMPOSER editable</Text></Box>,{stdout:out,stderr:out,stdin:input,debug:true,exitOnCtrlC:false});await pause();results.push({columns,rows,frame:last});app.unmount();}
 const out=new PassThrough();Object.assign(out,{columns:80,rows:24,isTTY:false});let frame='';out.on('data',b=>frame=b.toString());const input=new PassThrough();Object.assign(input,{isTTY:true,setRawMode(){},ref(){},unref(){}});const app=render(<Inspect reasoning={reasoning} lines={[]} width={76} maxLines={8}/>,{stdout:out,stderr:out,stdin:input,debug:true,exitOnCtrlC:false});await pause();const tail=frame;input.write('\\u001b[5~');await pause();const earlier=frame;input.write('\\u001b[6~');await pause();const returned=frame;app.unmount();console.log(JSON.stringify({results,tail,earlier,returned}));`);
 const run=spawnSync(process.execPath,[join(terminal,'node_modules/tsx/dist/cli.mjs'),script],{encoding:'utf8',timeout:15000});assert.equal(run.status,0,run.stderr);const output=JSON.parse(run.stdout.trim());for(const result of output.results){assert.match(result.frame,/KEEP_INTENT/);assert.match(result.frame,/A7/);assert.match(result.frame,/KEEP_COMPOSER/);assert.match(result.frame,/Reasoning/);assert.match(result.frame,/STEP_099/);assert.match(result.frame,/✓ Read/);assert.match(result.frame,/● Verify/);assert.ok(!result.frame.includes('STEP_000'));assert.ok(result.frame.trimEnd().split('\n').length<=result.rows);}assert.match(output.tail,/STEP_099/);assert.match(output.earlier,/STEP_091/);assert.ok(!output.earlier.includes('STEP_099'));assert.match(output.returned,/STEP_099/);
 }finally{rmSync(root,{recursive:true,force:true});}
});
