import {test} from 'node:test';import assert from 'node:assert/strict';import {mkdtempSync,writeFileSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join,resolve} from 'node:path';import {spawnSync} from 'node:child_process';import {edit,editorView,characters} from '../apps/terminal/src/components/editor.ts';import {completeCommand,findCommand} from '../apps/terminal/src/app/commands.ts';import {childEnv} from './fixtures/hermetic-env.ts';
test('Mac word editing preserves Unicode graphemes and native symbols',()=>{
 const text='café 👩🏽‍💻 deux mots';let p=edit(text,99,'word-left');assert.equal(p.cursor,12);p=edit(text,p.cursor,'word-backspace');assert.equal(p.text,'café 👩🏽‍💻 mots');assert.equal(edit('café 👩🏽‍💻',99,'word-backspace').text,'café ');assert.equal(edit('prix € @',0,'word-right').cursor,5);assert.equal(completeCommand('/res'),'/resume');assert.equal(completeCommand('/mo'),null);assert.equal(findCommand('history')?.action,'inspect');
});
test('rendered slash actions stay local, complete with Tab, inspect agents and preserve unknown input',()=>{
 const root=mkdtempSync(join(tmpdir(),'cs-command-ui-'));const terminal=resolve('apps/terminal');try{
 const script=join(root,'ui.tsx');writeFileSync(join(root,'package.json'),'{"type":"module"}');writeFileSync(script,`import React from ${JSON.stringify(join(terminal,'node_modules/react/index.js'))};import {render} from ${JSON.stringify(join(terminal,'node_modules/ink/build/index.js'))};import {App} from ${JSON.stringify(join(terminal,'src/app/App.tsx'))};import {createStore} from ${JSON.stringify(join(terminal,'src/app/store.ts'))};import {PassThrough} from 'node:stream';
 const store=createStore(),calls=[];let resumes=0,stops=0;const out=new PassThrough();Object.assign(out,{columns:80,rows:24,isTTY:false});let last='';out.on('data',b=>last=b.toString());const input=new PassThrough();Object.assign(input,{isTTY:true,setRawMode(){},ref(){},unref(){}});
 const app=render(<App store={store} producer={{say:t=>calls.push(t),choose(){},resume(){resumes++},cancel(){stops++},agentPage:()=>({digest:'1',offset:0,nextOffset:null,lines:['REAL_AGENT_PAGE']}),steer:t=>{calls.push('steer:'+t);return true}}}/>,{stdout:out,stderr:out,stdin:input,debug:true,exitOnCtrlC:false});const tick=()=>new Promise(r=>setTimeout(r,45));const key=async k=>{input.write(k);await tick()};await tick();await key('/res');await key('\\t');const completed=store.get().composer;await key('\\r');await key('/agents');await key('\\r');const agents=last;await key('\\x1b');await key('/missing');await key('\\r');const refused=last,retained=store.get().composer;await key('\\x15');store.send({type:'began'});await key('/motion off');await key('\\r');const reduced=last;await key('/stop');await key('\\r');await key('/context edit ID REV TEXT');await key('\\r');await key('/steer preserve my changes');await key('\\r');await key('café 🙂 deux mots');await key('\\x1bb');await key('\\x1b\\x7f');const words=store.get().composer;app.unmount();console.log(JSON.stringify({completed,agents,refused,retained,reduced,resumes,stops,calls,words}));`);
 const run=spawnSync(process.execPath,[join(terminal,'node_modules/tsx/dist/cli.mjs'),script],{encoding:'utf8',env:childEnv({home:root,sessions:root}),timeout:15000});assert.equal(run.status,0,run.stderr);const r=JSON.parse(run.stdout.trim());assert.equal(r.completed,'/resume');assert.equal(r.resumes,1);assert.match(r.agents,/REAL_AGENT_PAGE/);assert.match(r.refused,/Unknown command/);assert.equal(r.retained,'/missing');assert.match(r.reduced,/motion.*off/);assert.equal(r.stops,1);assert.equal(r.words,'café 🙂 mots');assert.deepEqual(r.calls,['/context edit ID REV TEXT','steer:preserve my changes']);
 }finally{rmSync(root,{recursive:true,force:true})}
});
test('semantic motion settles and reduced motion leaves no animation repaint loop',()=>{
 const root=mkdtempSync(join(tmpdir(),'cs-motion-'));const terminal=resolve('apps/terminal');try{const script=join(root,'motion.tsx');writeFileSync(join(root,'package.json'),'{"type":"module"}');writeFileSync(script,`import React from ${JSON.stringify(join(terminal,'node_modules/react/index.js'))};import {render} from ${JSON.stringify(join(terminal,'node_modules/ink/build/index.js'))};import {Header} from ${JSON.stringify(join(terminal,'src/components/Header.tsx'))};import {WorkContext} from ${JSON.stringify(join(terminal,'src/components/WorkContext.tsx'))};import {MotionContext} from ${JSON.stringify(join(terminal,'src/theme/motion.tsx'))};import {PassThrough} from 'node:stream';
 const out=new PassThrough();Object.assign(out,{columns:80,rows:24,isTTY:false});let frames=[];out.on('data',b=>frames.push(b.toString()));const input=new PassThrough();Object.assign(input,{isTTY:true,setRawMode(){},ref(){},unref(){}});const view=(model,on)=> <MotionContext.Provider value={on}><Header width={76} project={null} busy={false} model={model}/><WorkContext lines={['work','  └─ A1 · running']}/></MotionContext.Provider>;const app=render(view('first',true),{stdout:out,stderr:out,stdin:input,debug:true,exitOnCtrlC:false});const wait=ms=>new Promise(r=>setTimeout(r,ms));await wait(320);frames=[];app.rerender(view('second',true));await wait(320);const animated=[...frames];frames=[];app.rerender(view('third',false));await wait(80);const settled=frames.length;await wait(280);const final=frames.length;app.unmount();console.log(JSON.stringify({animated,settled,final}));`);
 const run=spawnSync(process.execPath,[join(terminal,'node_modules/tsx/dist/cli.mjs'),script],{encoding:'utf8',env:{...childEnv({home:root,sessions:root}),FORCE_COLOR:'3'},timeout:10000});assert.equal(run.status,0,run.stderr);const r=JSON.parse(run.stdout.trim());assert.ok(new Set(r.animated).size>=3,'route must contain intermediate color frames');assert.equal(r.final,r.settled,'no animation timer after reduced motion');assert.ok(r.animated.every((f:string)=>f.includes('second')&&f.includes('A1')),'complete semantic content remains visible through transition');
 }finally{rmSync(root,{recursive:true,force:true})}
});

test('long terminal drafts always retain the grapheme cursor inside the cell budget',()=>{
 for(const text of ['abc def ghi '.repeat(20),'café 👩🏽‍💻 世界 '.repeat(12)])for(const width of [4,12,36,76])for(let cursor=0;cursor<=characters(text).length;cursor++){const view=editorView(text,cursor,width);assert.ok(view.cells<=width,JSON.stringify({width,cursor,view}));assert.equal(view.cursor,characters(text)[cursor]??' ');}
 assert.equal(editorView('short',5,76).before,'short');
});
