import {partialProposalText} from '../src/adapters/opencode-stream.ts';
import {test} from 'node:test';import assert from 'node:assert/strict';import {mkdtempSync,writeFileSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';import {BinaryModelAdapter} from '../src/adapters/binary-model.ts';import {compileFrame,type ModelProgress} from '../src/core/loop.ts';import {EventStore} from '../src/core/store.ts';import {createStore} from '../apps/terminal/src/app/store.ts';import {createProducer} from '../apps/terminal/src/producer/index.ts';
const pause=(ms:number)=>new Promise(r=>setTimeout(r,ms));
test('owned SSE transport publishes reasoning and public text before final proposal',async()=>{const root=mkdtempSync(join(tmpdir(),'cs-progress-'));try{const binary=join(root,'fake');writeFileSync(binary,`#!${process.execPath}
const http=require('node:http');let stream;const server=http.createServer((req,res)=>{if(!req.headers.authorization){res.writeHead(401).end();return}if(req.url.startsWith('/event')){stream=res;res.writeHead(200,{'Content-Type':'text/event-stream'});res.write('data: '+JSON.stringify({type:'server.connected'})+'\\n\\n');return}if(req.url.startsWith('/session/s1/message')){const emit=(part)=>stream.write('data: '+JSON.stringify({type:'message.part.updated',properties:{part:{sessionID:'s1',...part}}})+'\\n\\n');emit({id:'r',type:'reasoning',text:'Étape publiée 🙂'});setTimeout(()=>emit({id:'t',type:'text',text:'{\\"text\\":\\"Bonjour'}),30);setTimeout(()=>{res.setHeader('content-type','application/json');res.end(JSON.stringify({info:{},parts:[{type:'text',text:JSON.stringify({text:'FINAL',toolCalls:[]})}]}))},400);return}res.setHeader('content-type','application/json');res.end(JSON.stringify({id:'s1'}))});server.listen(0,'127.0.0.1',()=>console.log('http://127.0.0.1:'+server.address().port));`,{mode:0o755});let complete=false;const observed:ModelProgress[]=[];const result=await new BinaryModelAdapter({binary,project:root}).infer(compileFrame(new EventStore('test').toSession(),{subject:'builder',goal:'read',maxSteps:1},1),undefined,p=>{assert.equal(complete,false);observed.push(p)});complete=true;assert.equal(result.text,'FINAL');assert.deepEqual(observed,[{kind:'reasoning',text:'Étape publiée 🙂'},{kind:'text',text:'Bonjour'}]);}finally{rmSync(root,{recursive:true,force:true})}});
test('producer publishes transient reasoning without committing it and ignores cancelled late blocks',async()=>{const root=mkdtempSync(join(tmpdir(),'cs-progress-ui-'));try{const store=createStore();let progress:((p:ModelProgress)=>void)|undefined;let release:any;const producer=createProducer({store,cwd:root,identities:[],projectsRoot:root,model:{name:'stream',infer(_f,_s,onProgress){progress=onProgress;return new Promise(r=>release=r)}},tools:{async run(r){return {name:r.name,exit:0,output:''}}}});producer.say('read');const deadline=Date.now()+2000;while(!progress&&Date.now()<deadline)await pause(10);assert.ok(progress);progress({kind:'reasoning',text:'Published step'});assert.equal(store.get().reasoning,'Published step');assert.ok(!store.get().entries.some(e=>'text' in e&&e.text==='Published step'));store.send({type:'compose',text:'editable now'});assert.equal(store.get().composer,'editable now');producer.cancel!();await pause(30);progress({kind:'reasoning',text:'late'});assert.equal(store.get().reasoning,'');release({text:'late final',toolCalls:[]});await pause(30);assert.equal(store.get().reasoning,'');}finally{rmSync(root,{recursive:true,force:true})}});

test('partial public text decodes escapes and hides proposal tools',()=>{assert.equal(partialProposalText('{"text":"hello\\nworld'), 'hello\nworld');assert.equal(partialProposalText('{"text":"hello\\u26'), 'hello');assert.equal(partialProposalText('{"toolCalls":[]}'), '');});

 test('provider retry stops owned inference promptly without exposing payloads or accepting a proposal',async()=>{
 const {providerEventFailure,ProviderProposalRefused}=await import('../src/adapters/opencode-stream.ts');
 const quota={type:'session.status',properties:{sessionID:'s1',status:{type:'retry',attempt:1,message:'Usage limit reached secret-api-key-DO-NOT-PRINT'}}};
 assert.equal(providerEventFailure(quota,'other'),null);assert.match(providerEventFailure(quota,'s1'),/Quota exhausted/);assert.doesNotMatch(providerEventFailure(quota,'s1'),/secret-api-key/);
 for(const [message,expected] of [['HTTP 429','rate limit'],['HTTP 401','authentication'],['HTTP 403','access refused'],['unclassified private payload','request failed']])assert.match(providerEventFailure({type:'session.error',properties:{sessionID:'s1',error:{data:{message}}}},'s1'),new RegExp(expected));
 const root=mkdtempSync(join(tmpdir(),'cs-provider-retry-'));try{
 const binary=join(root,'fake');writeFileSync(binary,`#!${process.execPath}
const http=require('node:http');let stream;const server=http.createServer((req,res)=>{if(!req.headers.authorization){res.writeHead(401).end();return}if(req.url.startsWith('/event')){stream=res;res.writeHead(200,{'Content-Type':'text/event-stream'});res.write('data: '+JSON.stringify({type:'server.connected'})+'\\n\\n');return}if(req.url.startsWith('/session/s1/message')){stream.write('data: '+JSON.stringify(${JSON.stringify({...quota,properties:{...quota.properties,sessionID:'foreign'}})})+'\\n\\n');setTimeout(()=>stream.write('data: '+JSON.stringify(${JSON.stringify(quota)})+'\\n\\n'),20);return}res.setHeader('content-type','application/json');res.end(JSON.stringify({id:'s1'}))});server.listen(0,'127.0.0.1',()=>console.log('http://127.0.0.1:'+server.address().port));`,{mode:0o755});
 const start=Date.now(),progress=[];
 await assert.rejects(()=>new BinaryModelAdapter({binary,project:root,timeoutMs:5000}).infer(compileFrame(new EventStore('retry').toSession(),{subject:'builder',goal:'read',maxSteps:1},1),undefined,p=>progress.push(p)),error=>{assert.ok(error instanceof ProviderProposalRefused);assert.match(error.message,/Quota exhausted/);assert.doesNotMatch(error.message,/secret-api-key/);return true;});
 assert.ok(Date.now()-start<2000);assert.deepEqual(progress,[]);
 }finally{rmSync(root,{recursive:true,force:true});}
 });
