import {test} from 'node:test';import assert from 'node:assert/strict';import {mkdtempSync,writeFileSync,rmSync} from 'node:fs';import {join,resolve} from 'node:path';import {tmpdir} from 'node:os';import {spawnSync} from 'node:child_process';import {childEnv} from './fixtures/hermetic-env.ts';
test('target work, filter, retain draft on refusal, detach and successfully submit at four sizes',()=>{
 const root=mkdtempSync(join(tmpdir(),'cs-px-')),terminal=resolve('apps/terminal');try{
 writeFileSync(join(root,'package.json'),'{"type":"module"}');const script=join(root,'px.tsx');writeFileSync(script,`
import React from ${JSON.stringify(join(terminal,'node_modules/react/index.js'))};import {render} from ${JSON.stringify(join(terminal,'node_modules/ink/build/index.js'))};import {App} from ${JSON.stringify(join(terminal,'src/app/App.tsx'))};import {createStore} from ${JSON.stringify(join(terminal,'src/app/store.ts'))};import {PassThrough} from 'node:stream';
const store=createStore();store.send({type:'submit',text:'Reliable restart'});store.send({type:'began'});store.send({type:'compose',text:'Preserve files'});let accept=false,calls=[];
const reference={id:'task:t1',source:3,objectiveId:'o1',objectiveRevision:2};const surface={intent:'Reliable restart',corrections:['Keep the public API'],criteria:['No duplicate write'],tasks:[],workers:[],objects:[{id:'task:t1',kind:'task',title:'Inspect replay',status:'planned',detail:'Expected: no duplicate writes',source:3,reference},{id:'contribution:c1',kind:'contribution',title:'Restart patch',status:'review required',detail:'Unverified contribution',source:4}]};
const producer={say(){throw Error('ordinary send must not receive targeted instruction')},choose(){},workSurface(){return surface},steerAt(ref,text){calls.push({ref,text});return accept?{ok:true}:{error:'This work changed. Inspect it again; your draft is preserved.'}}};
const out=new PassThrough();Object.assign(out,{columns:80,rows:24,isTTY:false});let frame='';out.on('data',b=>frame=b.toString());const input=new PassThrough();Object.assign(input,{isTTY:true,setRawMode(){},ref(){},unref(){}});const app=render(<App store={store} producer={producer}/>,{stdout:out,stderr:out,stdin:input,debug:true,exitOnCtrlC:false});const tick=()=>new Promise(r=>setTimeout(r,70)),key=async s=>{input.write(s);await tick()};
await tick();await key('\\t');await key('3');const results=frame;await key('2');const work=frame;await key('f');const focused=frame;await key('\\r');const refused=frame;await key('!');const afterRefusal=store.get().composer;await key('\\x1b');const detached=frame,draftAfterDetach=store.get().composer;
await key('\\t');await key('f');const sizes=[];for(const [columns,rows] of [[80,24],[120,30],[160,50],[240,70]]){out.columns=columns;out.rows=rows;out.emit('resize');await tick();sizes.push({rows,frame})};accept=true;await key('\\r');const submitted=frame,finalDraft=store.get().composer;app.unmount();console.log(JSON.stringify({results,work,focused,refused,afterRefusal,detached,draftAfterDetach,sizes,submitted,finalDraft,calls}));`);
 const run=spawnSync(process.execPath,[join(terminal,'node_modules/tsx/dist/cli.mjs'),script],{encoding:'utf8',timeout:15000,env:childEnv(root)});assert.equal(run.status,0,run.stderr);const r=JSON.parse(run.stdout.trim());
 assert.match(r.results,/Restart patch/);assert.doesNotMatch(r.results,/task · Inspect replay/);assert.match(r.work,/task · Inspect replay/);assert.doesNotMatch(r.work,/Restart patch/);assert.match(r.work,/Esc back/);assert.doesNotMatch(r.work,/Enter send/);
 assert.match(r.focused,/Reliable restart/);assert.match(r.focused,/Keep the public API/);assert.match(r.focused,/Target: Inspect replay/);assert.match(r.focused,/Enter correct selected work/);assert.match(r.refused,/work changed/);assert.equal(r.afterRefusal,'Preserve files!');assert.equal(r.draftAfterDetach,'Preserve files!');assert.doesNotMatch(r.detached,/Target:/);assert.equal(r.finalDraft,'');assert.equal(r.calls.length,2);assert.equal(r.calls[1].text,'Preserve files!');assert.equal(r.calls[1].ref.id,'task:t1');
 for(const {rows,frame} of r.sizes){assert.match(frame,/Target: Inspect replay/);assert.match(frame,/Preserve files!/);assert.ok(frame.trimEnd().split('\n').length<=rows,frame);}
 }finally{rmSync(root,{recursive:true,force:true});}
});
