import {readFileSync} from 'node:fs';import {test} from 'node:test';import assert from 'node:assert/strict';import {createSituation} from '../src/adapters/situation.ts';import {EventStore} from '../src/core/store.ts';import {withSharedContext} from '../src/adapters/shared-context.ts';import {createProducer} from '../apps/terminal/src/producer/index.ts';import {createStore} from '../apps/terminal/src/app/store.ts';import type {ContextFrame} from '../src/core/loop.ts';
const input={sessionId:'s',executionId:'e',workspace:'/project',launchDirectory:'/launch',objective:{id:'g',revision:1},role:'review',model:'fixture/model',lastHuman:{sourceSeq:1,text:'Bonjour, réponds en français'},peers:[]};
test('clock is fresh, UTC/Paris DST correct, labels explicit and locale never claims conversation language',()=>{
 let time=Date.parse('2026-03-29T00:30:00Z');const env={CUESHEET_TIME_ZONE:'Europe/Paris',CUESHEET_USER_LABEL:'Memo',CUESHEET_HOST_LABEL:'dev'};const snapshot=createSituation({env,now:()=>time,locale:'en-US',platform:'fixture'});const first=snapshot(input);assert.equal(first.time.local,'2026-03-29 01:30:00');assert.equal(first.time.offset,'GMT+01:00');assert.equal(first.time.utc,'2026-03-29T00:30:00.000Z');time+=3600000;const next=snapshot(input);assert.equal(next.time.local,'2026-03-29 03:30:00');assert.equal(next.time.offset,'GMT+02:00');assert.equal(next.locale,'en-US');assert.equal(next.responseLanguage.preference,null);assert.equal(next.responseLanguage.source,'conversation');assert.equal(next.human.label,'Memo');env.CUESHEET_USER_LABEL='changed';assert.equal(snapshot(input).human.label,'Memo');const unknown=createSituation({env:{},timeZone:'UTC',locale:'fr-FR',now:()=>time})(input);assert.equal(unknown.human.label,null);assert.equal(unknown.human.source,'unknown');assert.equal(createSituation({env:{CUESHEET_LANGUAGE:'fr-FR'},now:()=>time})(input).responseLanguage.preference,'fr-FR');
 for(const env of [{CUESHEET_TIME_ZONE:'invalid-zone'},{CUESHEET_LANGUAGE:'invalid_language'},{CUESHEET_USER_LABEL:'bad\x1b'}])assert.throws(()=>createSituation({env}));
});
test('situation survives frame compaction without mutating the event log',()=>{
 const log=new EventStore('s',Date.now);log.append({kind:'goal',subject:'builder',data:{text:'owner goal'}});for(let i=0;i<80;i++)log.append({kind:'observation',subject:'builder',data:{text:'history '.repeat(100)}});const s=createSituation({env:{},timeZone:'UTC',locale:'fr',now:()=>0})(input);const frame:ContextFrame={goal:'owner goal',history:log.toSession().events,directives:[],evidence:[],capabilities:[],model:'fixture',step:0};const before=log.revision;const result=withSharedContext(frame,log.toSession(),{maxChars:6000,situation:s});assert.ok(JSON.stringify(result).length<=6000);assert.match(JSON.stringify(result),/1970-01-01T00:00:00/);assert.match(JSON.stringify(result),/fixture\/model/);assert.equal(log.revision,before);
});
test('producer and consultants each receive current time, role, model and current human input without extra runs',async()=>{
 let time=1000,steps=0;const frames:ContextFrame[]=[];const view=createStore();const producer=createProducer({store:view,cwd:'/fixture/project',identities:[],maxSlices:1,now:()=>time,situation:createSituation({env:{CUESHEET_USER_LABEL:'Owner'},timeZone:'UTC',locale:'fr-FR',now:()=>time}),model:{name:'coordinator',async infer(frame){frames.push(frame);if(frame.directives.at(-1)!.text.includes('Consultation '))return {text:'analysis',toolCalls:[]};time+=1000;return {text:'',toolCalls:++steps===1?[{name:'consult_agents',input:{tasks:[{role:'review',task:'Review'}]}}]:[]};}},tools:{async run(){throw Error('no effects');}}});
 producer.say('Bonjour, conserve le contexte');const end=Date.now()+3000;while(view.get().busy&&Date.now()<end)await new Promise(r=>setTimeout(r,5));assert.equal(view.get().busy,false);const parse=(f:ContextFrame)=>JSON.parse(f.directives.find(d=>d.text.startsWith('Shared work snapshot.'))!.text.split('\n')[1]!).situation;const coordinator=frames.find(f=>!f.directives.at(-1)!.text.includes('Consultation '))!,consultant=frames.find(f=>f.directives.at(-1)!.text.includes('Consultation '))!;assert.equal(parse(coordinator).role,'coordinateur');assert.equal(parse(coordinator).time.epochMs,1000);assert.equal(parse(consultant).role,'review');assert.equal(parse(consultant).time.epochMs,2000);assert.equal(parse(consultant).workspace,'/fixture/project');assert.match(parse(consultant).lastHuman.text,/Bonjour/);assert.equal(parse(consultant).human.label,'Owner');const before=JSON.stringify(view.get());time+=1000;assert.match(producer.situationPage!().lines.join('\n'),/1970-01-01/);assert.equal(JSON.stringify(view.get()),before);
});

test('terminal launcher preserves only explicit situation configuration and OS locale keys',()=>{
 const launcher=readFileSync('src/surface-cli.ts','utf8');for(const key of ['LANG','LC_ALL','LC_MESSAGES','TZ','CUESHEET_TIME_ZONE','CUESHEET_LANGUAGE','CUESHEET_USER_LABEL','CUESHEET_HOST_LABEL'])assert.ok(launcher.includes('"'+key+'"'),key);
});
