import {test} from 'node:test';import assert from 'node:assert/strict';import {mkdtempSync,mkdirSync,writeFileSync,readFileSync,rmSync,symlinkSync,realpathSync} from 'node:fs';import {join} from 'node:path';import {tmpdir} from 'node:os';import {staticTypecheck,withStaticTypecheck} from '../src/adapters/typecheck.ts';
test('static checking reads the isolated source, preserves files and refuses escaped config paths',async()=>{
 const root=realpathSync(mkdtempSync(join(tmpdir(),'cs-static-'))),source=join(root,'source'),workspace=join(root,'isolated');try{mkdirSync(source);mkdirSync(workspace);mkdirSync(join(source,'node_modules'));symlinkSync(realpathSync('node_modules/typescript'),join(source,'node_modules/typescript'),'dir');for(const dir of [source,workspace]){writeFileSync(join(dir,'tsconfig.json'),JSON.stringify({compilerOptions:{strict:true,noEmit:true,types:[]},files:['example.ts']}));writeFileSync(join(dir,'example.ts'),'const value: number = 1;\n');}
 // The dependency symlink stays inside the trusted project root in production;
 // use a private copied compiler to make this fixture obey the same bound.
 const {cpSync}=await import('node:fs');rmSync(join(source,'node_modules/typescript'));cpSync(realpathSync('node_modules/typescript'),join(source,'node_modules/typescript'),{recursive:true});
 const delegated=[];const signal=new AbortController().signal;const runner=withStaticTypecheck(Object.assign({run:async request=>{delegated.push(request);return {name:request.name,exit:0,output:'delegated'};}},{names:['read_file']}),{source,workspace,signal});assert.deepEqual(runner.names,['read_file','check_types']);assert.equal((await runner.run({name:'read_file',input:{path:'example.ts'}})).output,'delegated');assert.equal(delegated.length,1);let result=await runner.run({name:'check_types',input:{project:'tsconfig.json'}});assert.equal(result.exit,0,result.output);writeFileSync(join(workspace,'example.ts'),'const value: number = "wrong";\n');result=await runner.run({name:'check_types',input:{project:'tsconfig.json'}});assert.equal(result.exit,2);assert.match(result.output,/not assignable/);assert.equal(readFileSync(join(source,'example.ts'),'utf8'),'const value: number = 1;\n');assert.equal(readFileSync(join(workspace,'example.ts'),'utf8'),'const value: number = "wrong";\n');assert.equal((await staticTypecheck({name:'check_types',input:{project:'../source/tsconfig.json'}},{source,workspace})).exit,126);symlinkSync(join(source,'tsconfig.json'),join(workspace,'escape.json'));assert.equal((await staticTypecheck({name:'check_types',input:{project:'escape.json'}},{source,workspace})).exit,126);
 }finally{rmSync(root,{recursive:true,force:true});}
});
