import {test} from 'node:test';import assert from 'node:assert/strict';
import {mkdtempSync,mkdirSync,writeFileSync,readFileSync,rmSync,realpathSync,unlinkSync,existsSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';import {execFileSync} from 'node:child_process';
import {captureGitSnapshot} from '../src/adapters/git-snapshot.ts';import {allocateWorktree} from '../src/adapters/managed-worktrees.ts';import {WorktreeReview,type ReviewBasis} from '../src/adapters/worktree-review.ts';import {childEnv} from './fixtures/hermetic-env.ts';
async function fixture(run:(o:{source:string;workspace:string;root:string;git:(...a:string[])=>string;review:WorktreeReview;basis:ReviewBasis;records:Record<string,unknown>[];busy(value:boolean):void})=>Promise<void>){
 const root=realpathSync(mkdtempSync(join(tmpdir(),'cs-review-'))),source=join(root,'source');mkdirSync(source);const git=(...a:string[])=>execFileSync('git',a,{cwd:source,env:childEnv({home:root,sessions:root}),encoding:'utf8'}).trim();
 try{git('init','-q');git('config','user.name','Fixture');git('config','user.email','fixture@example.invalid');writeFileSync(join(source,'file'),'base\n');writeFileSync(join(source,'delete'),'delete\n');git('add','.');git('commit','-qm','base');writeFileSync(join(source,'file'),'human dirty\n');writeFileSync(join(source,'owner'),'keep');git('add','owner');const snapshot=await captureGitSnapshot(source);const result=await allocateWorktree({repository:source,root:join(root,'worktrees'),allocation:{id:'review',unit:'review',agent:'worker',objective:'goal',revision:1,base:snapshot.base},snapshot});assert.equal(result.kind,'ready');if(result.kind!=='ready')return;
  const basis:ReviewBasis={source,workspace:result.path,sourceDigest:snapshot.digest,objective:'goal',revision:1,workspaceId:result.id};let busy=false;const records:Record<string,unknown>[]=[];const review=new WorktreeReview({root:join(root,'receipts'),basis:()=>basis,busy:()=>busy,record:data=>records.push(data)});await run({source,workspace:result.path,root,git,review,basis,records,busy:value=>{busy=value;}});
 }finally{rmSync(root,{recursive:true,force:true});}
}
test('human review shows contribution delta, applies exact plan and preserves original dirty index and HEAD',async()=>fixture(async({source,workspace,git,review,records})=>{
 const head=git('rev-parse','HEAD'),index=git('diff','--cached','--binary');writeFileSync(join(workspace,'file'),'human dirty\nagent edit\n');writeFileSync(join(workspace,'new'),'new\n');unlinkSync(join(workspace,'delete'));
 const opened=await review.open();assert.ok(opened);assert.deepEqual(opened.files.map(f=>f.path),['delete','file','new']);assert.match(opened.files.find(f=>f.path==='file')!.lines.join('\n'),/\+agent edit/);assert.equal(readFileSync(join(source,'file'),'utf8'),'human dirty\n');
 const applied=await review.decide(opened.token,opened.digest,'apply');assert.equal(applied.kind,'applied');assert.equal(readFileSync(join(source,'file'),'utf8'),'human dirty\nagent edit\n');assert.equal(readFileSync(join(source,'owner'),'utf8'),'keep');assert.equal(git('rev-parse','HEAD'),head);assert.equal(git('diff','--cached','--binary'),index);assert.equal(existsSync(join(source,'delete')),false);assert.equal(records[0]!.operation,'human-decision');assert.equal(records.at(-1)!.kind,'applied');await assert.rejects(review.decide(opened.token,opened.digest,'apply'),/expired/);
}));
test('busy, forged, revised and stale result decisions cannot apply',async()=>fixture(async({source,workspace,review,basis,busy})=>{
 writeFileSync(join(workspace,'file'),'agent edit\n');let opened=(await review.open())!;await assert.rejects(review.decide(opened.token,opened.digest,'invalid' as any),/Unknown review decision/);await assert.rejects(review.decide('forged',opened.digest,'apply'),/expired/);busy(true);await assert.rejects(review.decide(opened.token,opened.digest,'apply'),/Stop active/);busy(false);basis.revision++;await assert.rejects(review.decide(opened.token,opened.digest,'apply'),/intention/);opened=(await review.open())!;writeFileSync(join(workspace,'file'),'changed after preview');const result=await review.decide(opened.token,opened.digest,'apply');assert.equal(result.kind,'refused');assert.equal(readFileSync(join(source,'file'),'utf8'),'human dirty\n');
}));
test('source movement refuses preview and rejection preserves workspace files',async()=>fixture(async({source,workspace,review})=>{
 writeFileSync(join(workspace,'file'),'agent edit');const opened=(await review.open())!;assert.equal((await review.decide(opened.token,opened.digest,'reject')).kind,'rejected');assert.equal(readFileSync(join(workspace,'file'),'utf8'),'agent edit');assert.equal(readFileSync(join(source,'file'),'utf8'),'human dirty\n');writeFileSync(join(source,'file'),'new human work');const blocked=(await review.open())!;assert.match(blocked.blocked!,/no longer match/);await assert.rejects(review.decide(blocked.token,blocked.digest,'apply'),/cannot be applied/);assert.equal((await review.decide(blocked.token,blocked.digest,'reject')).kind,'rejected');assert.equal(readFileSync(join(source,'file'),'utf8'),'new human work');assert.equal(readFileSync(join(workspace,'file'),'utf8'),'agent edit');
}));
