import {test} from 'node:test';import assert from 'node:assert/strict';import {mkdtempSync,mkdirSync,writeFileSync,readFileSync,rmSync,realpathSync,existsSync,readdirSync,linkSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';import {execFileSync} from 'node:child_process';import {TerminalSession} from '../src/adapters/terminal-session.ts';import {ShellToolRunner} from '../src/adapters/shell.ts';import {createProducer} from '../apps/terminal/src/producer/index.ts';import {createStore} from '../apps/terminal/src/app/store.ts';import {childEnv} from './fixtures/hermetic-env.ts';
async function fixture(run:(source:string,root:string,git:(...a:string[])=>string)=>Promise<void>){const dir=realpathSync(mkdtempSync(join(tmpdir(),'cs-workspace-runtime-'))),source=join(dir,'source'),root=join(dir,'state');mkdirSync(source);const git=(...a:string[])=>execFileSync('git',a,{cwd:source,env:childEnv({home:dir,sessions:root}),encoding:'utf8'}).trim();try{git('init','-q');git('config','user.name','Fixture');git('config','user.email','fixture@example.invalid');writeFileSync(join(source,'file'),'base');git('add','.');git('commit','-qm','base');await run(source,root,git);}finally{rmSync(dir,{recursive:true,force:true});}}
const wait=async(view:ReturnType<typeof createStore>)=>{const until=Date.now()+8000;while(view.get().busy&&Date.now()<until)await new Promise(r=>setTimeout(r,10));assert.equal(view.get().busy,false);};
function setup(source:string,root:string,journal:TerminalSession,model:any){const view=createStore();const factory=(scope:string)=>Object.assign(new ShellToolRunner({allow:['node','cat','ls'],roots:[scope],defaultCwd:scope,env:childEnv({home:root,sessions:root})}),{names:['node','cat','ls']});return {view,producer:createProducer({store:view,journal,cwd:source,identities:[],maxSlices:1,worktreeRoot:join(root,'workspaces',journal.metadata.id),toolsForScope:factory,tools:factory(source),model})};}
test('real producer selects dirty-preserving worktree, retargets actual shell, rejects old-batch action and keeps goal open',async()=>fixture(async(source,root,git)=>{writeFileSync(join(source,'file'),'human');writeFileSync(join(source,'owner-note'),'keep');const before=git('status','--porcelain');const journal=new TerminalSession({root,cwd:source});try{let step=0;const frames:any[]=[];const {view,producer}=setup(source,root,journal,{name:'fixture',async infer(frame:any){frames.push(frame);step++;if(step===1)return {text:'',toolCalls:[{name:'prepare_workspace',input:{unit:'implement test'}},{name:'node',input:{argv:['node','-e',"require('fs').writeFileSync('old-batch','unsafe')"]}}]};if(step===2)return {text:'',toolCalls:[{name:'node',input:{argv:['node','-e',"require('fs').writeFileSync('result','coded')"]}}]};if(step===3)return {text:'',toolCalls:[{name:'finish',input:{}}]};return {text:'',toolCalls:[]};}});producer.say('qzworkspace fixture');await wait(view);const selected=journal.core.toSession().events.filter(e=>e.subject==='terminal.workspace'&&e.data.phase==='selected').at(-1)!;assert.ok(selected);const path=String(selected.data.path);assert.equal(readFileSync(join(path,'result'),'utf8'),'coded');assert.equal(readFileSync(join(path,'file'),'utf8'),'human');assert.equal(readFileSync(join(path,'owner-note'),'utf8'),'keep');assert.equal(existsSync(join(path,'old-batch')),false);assert.equal(existsSync(join(source,'result')),false);assert.equal(git('status','--porcelain'),before);assert.equal(journal.core.toSession().goal!.open,true);assert.ok(frames.some(f=>JSON.stringify(f).includes('Controller active workspace: '+path)));const page=producer.workspacePage!();assert.match(page.lines.join('\n'),/Verification and integration required/);assert.equal(page.lines.filter(l=>l.startsWith('Workspace : ')).length,1);const revision=journal.core.toSession().events.length;assert.equal(producer.workspacePage!(),page,'stable page cache avoids repeated projections');assert.equal(journal.core.toSession().events.length,revision,'read-only page');const observations=journal.core.toSession().events.filter(e=>e.kind==='observation');assert.ok(observations.some(e=>e.data.tool==='finish'&&e.data.exit===126));}finally{journal.close();}}));
test('explicit resume reattaches dirty worktree; moved source blocks without fallback writes',async()=>fixture(async(source,root)=>{let journal=new TerminalSession({root,cwd:source});const id=journal.metadata.id;let step=0;let first=setup(source,root,journal,{name:'fixture',async infer(){if(++step===1)return {text:'',toolCalls:[{name:'prepare_workspace',input:{unit:'build'}}]};return {text:'',toolCalls:[]};}});first.producer.say('qzresume fixture');await wait(first.view);const path=String(journal.core.toSession().events.find(e=>e.subject==='terminal.workspace'&&e.data.phase==='selected')!.data.path);writeFileSync(join(path,'pending'),'preserve');journal.close();journal=new TerminalSession({root,cwd:source,id});try{let calls=0;const resumed=setup(source,root,journal,{name:'fixture',async infer(frame:any){calls++;assert.match(JSON.stringify(frame),new RegExp(path.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')));return {text:'',toolCalls:[]};}});resumed.producer.resume!();await wait(resumed.view);assert.ok(calls>0);assert.equal(readFileSync(join(path,'pending'),'utf8'),'preserve');writeFileSync(join(source,'changed'),'human new source');calls=0;resumed.producer.resume!();await wait(resumed.view);assert.equal(calls,0);assert.match(resumed.view.get().entries.map(e=>'text' in e?e.text:'').join('\n'),/Source changed since isolation/);assert.equal(existsSync(join(source,'pending')),false);}finally{journal.close();}}));

for(const automatic of [false,true])test(`human correction during ${automatic?'automatic':'explicit'} allocation never retargets the obsolete preparation`,async()=>fixture(async(source,root,git)=>{const journal=new TerminalSession({root,cwd:source});try{let calls=0;const {view,producer}=setup(source,root,journal,{name:'fixture',async infer(){return {text:'',toolCalls:++calls===1?[automatic?{name:'node',input:{argv:['node','-e',"require('fs').writeFileSync('stale','bad')"]}}:{name:'prepare_workspace',input:{unit:'build'}}]:[]};}});producer.say('qzstale workspace fixture');const until=Date.now()+6000;const dir=join(root,'workspaces',journal.metadata.id);while(Date.now()<until&&(!existsSync(dir)||!readdirSync(dir).some(n=>n.endsWith('.jsonl'))))await new Promise(r=>setTimeout(r,5));assert.ok(existsSync(dir));producer.say('Correction: conserve le projet original intact');await wait(view);assert.equal(journal.core.toSession().events.filter(e=>e.subject==='terminal.workspace'&&e.data.phase==='selected').length,0);assert.equal(git('status','--porcelain'),'');assert.equal(journal.core.toSession().events.filter(e=>e.kind==='effect_requested'&&e.data.effect==='RunAgent').length,1);assert.ok(journal.core.toSession().events.some(e=>e.kind==='directive'&&String(e.data.text).includes('Correction:')));}finally{journal.close();}}));

test('refused isolated preparation blocks provider source mutations and finish, including after reload',async()=>fixture(async(source,root,git)=>{git('update-ref','-d','HEAD');let journal=new TerminalSession({root,cwd:source});const id=journal.metadata.id;try{let step=0;const first=setup(source,root,journal,{name:'fixture',async infer(){step++;return {text:'',toolCalls:step===1?[{name:'prepare_workspace',input:{unit:'build'}}]:step===2?[{name:'node',input:{argv:['node','-e',"require('fs').writeFileSync('forbidden','bad')"]}},{name:'cat',input:{path:'file'}},{name:'finish',input:{}}]:[]};}});first.producer.say('qzrefused fixture');await wait(first.view);let events=journal.core.toSession().events;assert.ok(events.some(e=>e.subject==='terminal.workspace'&&e.data.phase==='refused'));assert.ok(events.some(e=>e.kind==='observation'&&e.data.tool==='node'&&e.data.exit===126));assert.ok(events.some(e=>e.kind==='observation'&&e.data.tool==='cat'&&e.data.exit===0));assert.ok(events.some(e=>e.kind==='observation'&&e.data.tool==='finish'&&e.data.exit===126));assert.equal(existsSync(join(source,'forbidden')),false);assert.equal(journal.core.toSession().goal!.open,true);journal.close();journal=new TerminalSession({root,cwd:source,id});let calls=0;const resumed=setup(source,root,journal,{name:'fixture',async infer(){return {text:'',toolCalls:++calls===1?[{name:'node',input:{argv:['node','-e',"require('fs').writeFileSync('forbidden','bad')"]}}]:[]};}});resumed.producer.resume!();await wait(resumed.view);assert.equal(existsSync(join(source,'forbidden')),false);assert.equal(journal.core.toSession().goal!.open,true);}finally{journal.close();}}));

test('controller isolates first code command without model preparation and discards the old batch',async()=>fixture(async(source,root,git)=>{
  writeFileSync(join(source,'file'),'human dirty');writeFileSync(join(source,'owner-note'),'preserve');git('add','file');const before=git('status','--porcelain'),index=git('diff','--cached');
  const journal=new TerminalSession({root,cwd:source});try{let step=0;const command={name:'node',input:{argv:['node','-e',"require('fs').writeFileSync('result','coded')"]}};
    const {view,producer}=setup(source,root,journal,{name:'forgetful',async infer(){step++;return {text:'',toolCalls:step===1?[command,{name:'node',input:{argv:['node','-e',"require('fs').writeFileSync('stale','bad')"]}}]:step===2?[command]:[]};}});
    producer.say('qzautomatic isolation');await wait(view);const events=journal.core.toSession().events;const selected=events.find(e=>e.subject==='terminal.workspace'&&e.data.phase==='selected')!;assert.ok(selected);const child=String(selected.data.path);
    assert.equal(readFileSync(join(child,'result'),'utf8'),'coded');assert.equal(readFileSync(join(child,'file'),'utf8'),'human dirty');assert.equal(readFileSync(join(child,'owner-note'),'utf8'),'preserve');assert.equal(existsSync(join(child,'stale')),false);assert.equal(existsSync(join(source,'result')),false);assert.equal(git('status','--porcelain'),before);assert.equal(git('diff','--cached'),index);
    const intents=events.filter(e=>e.subject==='terminal.intent'&&e.data.tool==='node');assert.equal(intents.length,1);assert.equal(intents[0]!.data.scopeCwd,child);assert.ok(events.some(e=>e.kind==='observation'&&e.data.tool==='node'&&e.data.exit===126));assert.equal(journal.core.toSession().goal!.open,true);
  }finally{journal.close();}
}));
test('shared reading never allocates a worktree',async()=>fixture(async(source,root)=>{
  const journal=new TerminalSession({root,cwd:source});try{let step=0;const {view,producer}=setup(source,root,journal,{name:'reader',async infer(){return {text:'',toolCalls:++step===1?[{name:'cat',input:{path:'file'}}]:[]};}});producer.say('qzread only');await wait(view);assert.equal(journal.core.toSession().events.filter(e=>e.subject==='terminal.workspace').length,0);assert.equal(existsSync(join(root,'workspaces')),false);}finally{journal.close();}
}));
test('automatic code admission refuses unborn Git without source fallback',async()=>fixture(async(source,root,git)=>{
  git('update-ref','-d','HEAD');const journal=new TerminalSession({root,cwd:source});try{let step=0;const {view,producer}=setup(source,root,journal,{name:'forgetful',async infer(){return {text:'',toolCalls:++step<3?[{name:'node',input:{argv:['node','-e',"require('fs').writeFileSync('forbidden','bad')"]}}]:[]};}});producer.say('qzautomatic unborn');await wait(view);assert.equal(existsSync(join(source,'forbidden')),false);assert.ok(journal.core.toSession().events.some(e=>e.subject==='terminal.workspace'&&e.data.phase==='refused'));assert.equal(journal.core.toSession().goal!.open,true);}finally{journal.close();}
}));

test('confirmed non-Git workspace keeps scoped code execution without allocation',async()=>{
  const dir=realpathSync(mkdtempSync(join(tmpdir(),'cs-nongit-runtime-'))),source=join(dir,'source'),root=join(dir,'state');mkdirSync(source);const journal=new TerminalSession({root,cwd:source});try{let step=0;const {view,producer}=setup(source,root,journal,{name:'nonGit',async infer(){return {text:'',toolCalls:++step===1?[{name:'node',input:{argv:['node','-e',"require('fs').writeFileSync('result','coded')"]}}]:[]};}});producer.say('qznonGit compatibility');await wait(view);assert.equal(readFileSync(join(source,'result'),'utf8'),'coded');assert.equal(journal.core.toSession().events.filter(e=>e.subject==='terminal.workspace').length,0);}finally{journal.close();rmSync(dir,{recursive:true,force:true});}
});


test('real Docker inspection isolates dirty Git with ignored hardlinked dependencies, then executes edits without touching source',{skip:!process.env.CUESHEET_TEST_TOOL_SOCKET},async()=>fixture(async(source,root,git)=>{
 const {createScopedToolRunner}=await import('../apps/terminal/src/producer/runtime.ts');const {DEFAULT_TOOL_IMAGE}=await import('../src/adapters/tool-route.ts');
 writeFileSync(join(source,'.gitignore'),'node_modules/\n');mkdirSync(join(source,'node_modules'));writeFileSync(join(source,'node_modules','linked'),'dependency');linkSync(join(source,'node_modules','linked'),join(source,'node_modules','alias'));writeFileSync(join(source,'file'),'human dirty');writeFileSync(join(source,'owner-note'),'preserve');const before=git('status','--porcelain'),index=git('diff','--cached'),head=git('rev-parse','HEAD');
 const journal=new TerminalSession({root,cwd:source});try{const view=createStore();const factory=(scope:string)=>createScopedToolRunner({scope,journal,route:{kind:'container',socket:process.env.CUESHEET_TEST_TOOL_SOCKET!,image:DEFAULT_TOOL_IMAGE,defaultImage:true,reason:'fixture owned container'}});let step=0;
 const producer=createProducer({store:view,journal,cwd:source,identities:[],maxSlices:1,worktreeRoot:join(root,'workspaces',journal.metadata.id),toolsForScope:factory,tools:factory(source),model:{name:'transport fixture',async infer(){step++;return {text:step===5?'Contribution ready for review':'',toolCalls:step<=2?[{name:'ls',input:{argv:['ls','-la']}}]:step===3?[{name:'node',input:{argv:['node','-e',"require('fs').writeFileSync('isolated-result','actual container edit')"]}}]:step===4?[{name:'cat',input:{path:'isolated-result'}}]:[]};}}});
 producer.say('qz real container inspection and edit');await wait(view);const events=journal.core.toSession().events;const selected=events.find(e=>e.subject==='terminal.workspace'&&e.data.phase==='selected');assert.ok(selected);const workspace=String(selected.data.path);
 assert.equal(readFileSync(join(workspace,'isolated-result'),'utf8'),'actual container edit');assert.equal(existsSync(join(source,'isolated-result')),false);assert.equal(readFileSync(join(source,'file'),'utf8'),'human dirty');assert.equal(readFileSync(join(workspace,'owner-note'),'utf8'),'preserve');assert.equal(git('status','--porcelain'),before);assert.equal(git('diff','--cached'),index);assert.equal(git('rev-parse','HEAD'),head);assert.ok(events.some(e=>e.kind==='observation'&&e.data.tool==='ls'&&e.data.exit===0));assert.ok(events.some(e=>e.kind==='observation'&&e.data.tool==='cat'&&e.data.exit===0));assert.ok(events.filter(e=>e.subject==='terminal.intent'&&['ls','node','cat'].includes(String(e.data.tool))).every(e=>e.data.scopeCwd===workspace));assert.equal(journal.core.toSession().goal!.open,true);
 }finally{journal.close();}
}));

test('ordinary continuation reuses pending files, review applies only contribution and restart does not replay effects',async()=>fixture(async(source,root,git)=>{
 writeFileSync(join(source,'file'),'human dirty');git('add','file');const head=git('rev-parse','HEAD'),index=git('diff','--cached');let journal=new TerminalSession({root,cwd:source});const id=journal.metadata.id;
 try{let step=0;const first=setup(source,root,journal,{name:'fixture',async infer(){return {text:'',toolCalls:++step<=2?[{name:'node',input:{argv:['node','-e',"require('fs').writeFileSync('contribution','first')"]}}]:[]};}});first.producer.say('implement contribution');await wait(first.view);const path=String(journal.core.toSession().events.find(e=>e.subject==='terminal.workspace'&&e.data.phase==='selected')!.data.path);
 step=10;first.producer.say('continue and preserve it');await wait(first.view);assert.equal(String(journal.core.toSession().events.filter(e=>e.subject==='terminal.workspace'&&e.data.phase==='selected').at(-1)!.data.path),path);assert.equal(readFileSync(join(path,'contribution'),'utf8'),'first');
 const preview=await first.producer.changes!();assert.ok(preview);assert.deepEqual(preview.files.map(f=>f.path),['contribution']);assert.equal(existsSync(join(source,'contribution')),false);assert.equal((await first.producer.decideChanges!(preview.token,preview.digest,'apply')).kind,'applied');assert.equal(readFileSync(join(source,'contribution'),'utf8'),'first');assert.equal(git('rev-parse','HEAD'),head);assert.equal(git('diff','--cached'),index);assert.equal(journal.core.toSession().goal!.open,true);const effects=journal.core.toSession().events.filter(e=>e.kind==='effect_requested').length;
 journal.close();journal=new TerminalSession({root,cwd:source,id});let calls=0;const reloaded=setup(source,root,journal,{name:'fixture',async infer(){calls++;return {text:'',toolCalls:[]};}});assert.equal(calls,0);assert.equal(journal.core.toSession().events.filter(e=>e.kind==='effect_requested').length,effects);assert.equal(await reloaded.producer.changes!(),null);
 }finally{journal.close();}
}));
test('setting contribution aside preserves files across restart without offering or applying them again',async()=>fixture(async(source,root)=>{
 let journal=new TerminalSession({root,cwd:source});const id=journal.metadata.id;try{let step=0;const first=setup(source,root,journal,{name:'fixture',async infer(){return {text:'',toolCalls:++step<=2?[{name:'node',input:{argv:['node','-e',"require('fs').writeFileSync('contribution','preserved')"]}}]:[]};}});first.producer.say('implement contribution');await wait(first.view);const preview=(await first.producer.changes!())!;const path=preview.workspace;assert.equal((await first.producer.decideChanges!(preview.token,preview.digest,'reject')).kind,'rejected');assert.equal(readFileSync(join(path,'contribution'),'utf8'),'preserved');assert.equal(existsSync(join(source,'contribution')),false);journal.close();journal=new TerminalSession({root,cwd:source,id});const reloaded=setup(source,root,journal,{name:'fixture',async infer(){return {text:'',toolCalls:[]};}});assert.equal(await reloaded.producer.changes!(),null);assert.equal(readFileSync(join(path,'contribution'),'utf8'),'preserved');
 }finally{journal.close();}
}));

test('starting from home binds the named project and generic review continuation keeps its isolated contribution',async()=>fixture(async(source,root)=>{
 const home=join(root,'home');mkdirSync(home,{recursive:true});const journal=new TerminalSession({root:join(root,'sessions'),cwd:home});try{const view=createStore();let step=0;const factory=(scope:string)=>Object.assign(new ShellToolRunner({allow:['node'],roots:[scope],defaultCwd:scope,env:childEnv({home:root,sessions:root})}),{names:['node']});const producer=createProducer({store:view,journal,cwd:home,projectsRoot:join(source,'..'),identities:[{name:'fixture-cuesheet',path:'source',kind:'repo',status:'live',nature:'tool',stack:'typescript',exists:true},{name:'other-review',path:'other',kind:'repo',status:'live',nature:'review',stack:'safety',exists:false}],maxSlices:1,worktreeRoot:join(root,'workspaces',journal.metadata.id),tools:factory(home),toolsForScope:factory,model:{name:'fixture',async infer(){return {text:'',toolCalls:++step<=2?[{name:'node',input:{argv:['node','-e',"require('fs').writeFileSync('contribution','preserve')"]}}]:[]};}}});producer.say('work on fixture-cuesheet');await wait(view);const selected=journal.core.toSession().events.filter(e=>e.subject==='terminal.workspace'&&e.data.phase==='selected').at(-1)!;assert.equal(selected.data.source,source);producer.say('review the safety of this contribution');await wait(view);assert.equal(journal.core.toSession().events.filter(e=>e.subject==='terminal.workspace'&&e.data.phase==='selected').at(-1)!.data.path,selected.data.path);assert.equal(readFileSync(join(String(selected.data.path),'contribution'),'utf8'),'preserve');assert.equal(existsSync(join(home,'contribution')),false);assert.equal(existsSync(join(source,'contribution')),false);assert.equal(view.get().overlay,'none');}finally{journal.close();}
}));

test('an uncertain partial application blocks further inference and source effects',async()=>fixture(async(source,root)=>{
 const journal=new TerminalSession({root,cwd:source});try{journal.core.append({kind:'note',subject:'terminal.workspace',data:{version:1,phase:'uncertain',source,path:join(root,'preserved')}});let calls=0;const {view,producer}=setup(source,root,journal,{name:'fixture',async infer(){calls++;return {text:'',toolCalls:[]};}});producer.say('continue fixture');await wait(view);assert.equal(calls,0);assert.match(view.get().entries.map(e=>'text' in e?e.text:'').join('\n'),/partial application needs receipt inspection/);assert.equal(readFileSync(join(source,'file'),'utf8'),'base');}finally{journal.close();}
}));

 test("an unresolved real home scope cannot authorize code effects",async()=>{
 const {homedir}=await import('node:os');const view=createStore();let step=0,calls=0;const producer=createProducer({store:view,cwd:homedir(),identities:[],maxSlices:1,model:{name:"fixture",async infer(){return {text:"",toolCalls:++step===1?[{name:"node",input:{argv:["node","-e","throw Error('must not execute')"]}}]:[]};}},tools:{async run(){calls++;throw Error("Home tool must not run");}}});producer.say("implement this unnamed feature");await wait(view);assert.equal(calls,0);assert.match(view.get().entries.map(e=>e.kind==="action"?e.detail??"":"text"in e?e.text:"").join("\n"),/home directory is not a project write scope/);
});
