import {test} from 'node:test';import assert from 'node:assert/strict';import {mkdtempSync,mkdirSync,writeFileSync,readFileSync,rmSync,realpathSync,unlinkSync,existsSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';import {execFileSync} from 'node:child_process';import {captureGitSnapshot} from '../src/adapters/git-snapshot.ts';import {allocateWorktree} from '../src/adapters/managed-worktrees.ts';import {planWorktreeIntegration,applyWorktreeIntegration,composeWorktreePlans} from '../src/adapters/worktree-integration.ts';import {childEnv} from './fixtures/hermetic-env.ts';
async function fixture(run:(source:string,workspace:string,root:string,git:(...a:string[])=>string,digest:string)=>Promise<void>){const root=realpathSync(mkdtempSync(join(tmpdir(),'cs-integrate-'))),source=join(root,'source');mkdirSync(source);const git=(...a:string[])=>execFileSync('git',a,{cwd:source,env:childEnv({home:root,sessions:root}),encoding:'utf8'}).trim();try{git('init','-q');git('config','user.name','Fixture');git('config','user.email','fixture@example.invalid');writeFileSync(join(source,'file'),'base');writeFileSync(join(source,'delete'),'old');git('add','.');git('commit','-qm','base');writeFileSync(join(source,'file'),'human');writeFileSync(join(source,'human-staged'),'keep');git('add','human-staged');const snapshot=await captureGitSnapshot(source);const result=await allocateWorktree({repository:source,root:join(root,'worktrees'),allocation:{id:'build',unit:'build',agent:'worker',objective:'goal',revision:1,base:snapshot.base},snapshot});assert.equal(result.kind,'ready');if(result.kind==='ready')await run(source,result.path,root,git,snapshot.digest);}finally{rmSync(root,{recursive:true,force:true});}}
test('applies attributed modified/new/deleted delta, preserves source index/HEAD and durable before/after plan',async()=>fixture(async(source,workspace,root,git,digest)=>{const head=git('rev-parse','HEAD'),index=git('diff','--cached','--binary');writeFileSync(join(workspace,'file'),'coded');writeFileSync(join(workspace,'new'),'new code');unlinkSync(join(workspace,'delete'));const plan=await planWorktreeIntegration({source,workspace,sourceDigest:digest});assert.equal(plan.files.length,3);const result=await applyWorktreeIntegration(plan,{root:join(root,'receipts'),current:()=>true});assert.equal(result.kind,'applied',JSON.stringify(result));assert.equal(readFileSync(join(source,'file'),'utf8'),'coded');assert.equal(readFileSync(join(source,'new'),'utf8'),'new code');assert.equal(existsSync(join(source,'delete')),false);assert.equal(readFileSync(join(source,'human-staged'),'utf8'),'keep');assert.equal(git('rev-parse','HEAD'),head);assert.equal(git('diff','--cached','--binary'),index);assert.ok(result.record);const receipts=readFileSync(result.record!,'utf8').trim().split('\n').map(s=>JSON.parse(s));assert.equal(receipts[0].phase,'planned');assert.equal(receipts[0].plan.files.find((f:any)=>f.path==='file').before.bytes,Buffer.from('human').toString('base64'));assert.equal(receipts.at(-1).phase,'applied');}));
test('source/result drift or forged plan refuses before changes and leaves work inspectable',async()=>fixture(async(source,workspace,root,_git,digest)=>{writeFileSync(join(workspace,'file'),'coded');const plan=await planWorktreeIntegration({source,workspace,sourceDigest:digest});assert.equal((await applyWorktreeIntegration({...plan},{root:join(root,'r'),current:()=>true})).kind,'refused');writeFileSync(join(source,'file'),'new human correction');assert.equal((await applyWorktreeIntegration(plan,{root:join(root,'r'),current:()=>true})).kind,'refused');assert.equal(readFileSync(join(source,'file'),'utf8'),'new human correction');await assert.rejects(planWorktreeIntegration({source,workspace,sourceDigest:digest}),/no longer match/);}));
test('correction after first file records uncertain effect and never overwrites remaining source',async()=>fixture(async(source,workspace,root,_git,digest)=>{writeFileSync(join(workspace,'file'),'coded');writeFileSync(join(workspace,'new'),'new code');const plan=await planWorktreeIntegration({source,workspace,sourceDigest:digest});const current=()=>readFileSync(join(source,'file'),'utf8')==='human';const result=await applyWorktreeIntegration(plan,{root:join(root,'r'),current});assert.equal(result.kind,'uncertain');assert.equal(result.files,1);assert.equal(readFileSync(join(source,'file'),'utf8'),'coded');assert.equal(existsSync(join(source,'new')),false);assert.ok(result.record);}));
test('repository claim and uncovered credential file refuse instead of bypassing checks',async()=>fixture(async(source,workspace,root,git,digest)=>{writeFileSync(join(workspace,'file'),'coded');const plan=await planWorktreeIntegration({source,workspace,sourceDigest:digest});const lock=join(source,'.git','cuesheet-integration.lock');writeFileSync(lock,'external controller');assert.equal((await applyWorktreeIntegration(plan,{root:join(root,'r'),current:()=>true})).kind,'refused');assert.equal(readFileSync(lock,'utf8'),'external controller');unlinkSync(lock);writeFileSync(join(workspace,'.env'),'DO_NOT_READ=fixture');await assert.rejects(planWorktreeIntegration({source,workspace,sourceDigest:digest}),/Uncovered/);assert.equal(git('rev-parse','HEAD'),plan.source.base);assert.equal(readFileSync(join(source,'file'),'utf8'),'human');}));

test('malformed plan and correction immediately before deletion refuse without deleting source',async()=>fixture(async(source,workspace,root,_git,digest)=>{assert.equal((await applyWorktreeIntegration({} as any,{root:join(root,'r'),current:()=>true})).kind,'refused');unlinkSync(join(workspace,'delete'));const plan=await planWorktreeIntegration({source,workspace,sourceDigest:digest});let checks=0;const result=await applyWorktreeIntegration(plan,{root:join(root,'r'),current:()=>++checks<3});assert.equal(result.kind,'refused');assert.equal(result.files,0);assert.equal(readFileSync(join(source,'delete'),'utf8'),'old');}));

 test('composition refuses conflicting real worker deltas before writing any composed file',async()=>fixture(async(source,workspace,root,_git,digest)=>{
 const snapshot=await captureGitSnapshot(source);const allocations=[];
 for(const id of ['second-worker','composition']){const result=await allocateWorktree({repository:source,root:join(root,'worktrees'),allocation:{id,unit:id,agent:'fixture',objective:'goal',revision:1,base:snapshot.base},snapshot});assert.equal(result.kind,'ready');if(result.kind!=='ready')return;allocations.push(result.path);}
 writeFileSync(join(workspace,'file'),'worker one');writeFileSync(join(allocations[0],'file'),'worker two');
 const plans=await Promise.all([workspace,allocations[0]].map(path=>planWorktreeIntegration({source,workspace:path,sourceDigest:digest})));
 await assert.rejects(composeWorktreePlans(plans,allocations[1]),/Conflicting/);
 assert.equal(readFileSync(join(source,'file'),'utf8'),'human');assert.equal(readFileSync(join(allocations[1],'file'),'utf8'),'human');
 }));
