/** Explicit local pilot: requires pinned image/socket/binary; never changes owner preferences. */
import {mkdtempSync,realpathSync,mkdirSync,writeFileSync,readFileSync,existsSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';import {execFileSync} from 'node:child_process';import {createProducer} from '../apps/terminal/src/producer/index.ts';import {createStore} from '../apps/terminal/src/app/store.ts';import {TerminalSession} from '../src/adapters/terminal-session.ts';import {createCompletionCheck} from '../src/adapters/surface-verification.ts';import {ContainerToolRunner} from '../src/adapters/container-tools.ts';import {BinaryModelAdapter} from '../src/adapters/binary-model.ts';import {ResearchTools} from '../src/adapters/research-tools.ts';
const image=process.env.CUESHEET_TEST_CAPSULE_IMAGE,socket=process.env.CUESHEET_TEST_TOOL_SOCKET,binary=process.env.CUESHEET_OPENCODE_BIN;if(!image||!socket||!binary)throw Error('Explicit capsule image, local socket and binary required.');
if(!process.env.CUESHEET_PILOT_HOME_ISOLATED||process.env.OPENROUTER_API_KEY||process.env.ANTHROPIC_API_KEY||process.env.OPENAI_API_KEY)throw Error('Run in explicitly isolated environment without paid credentials.');
const config=JSON.parse(process.env.OPENCODE_CONFIG_CONTENT??'{}');if(config.model!=='opencode/big-pickle'||config.small_model!=='opencode/big-pickle'||JSON.stringify(config.enabled_providers)!=='["opencode"]')throw Error('Pilot main/auxiliary model must be pinned to the same free-listed provider.');
const root=realpathSync(mkdtempSync(join(tmpdir(),'cs-free-pilot-'))),source=join(root,'source'),state=join(root,'state');mkdirSync(source);const git=(...args:string[])=>execFileSync('git',args,{cwd:source,env:{PATH:process.env.PATH!,HOME:root,GIT_CONFIG_GLOBAL:'/dev/null',GIT_CONFIG_NOSYSTEM:'1'},encoding:'utf8'}).trim();
writeFileSync(join(source,'.gitignore'),'node_modules/\n.cuesheet/\n');writeFileSync(join(source,'clamp.mjs'),'export function clamp(value,min,max){return value;}\n');const tests=`import {test} from 'node:test';import assert from 'node:assert/strict';import {clamp} from './clamp.mjs';test('clamp lower/interior/upper',()=>{assert.equal(clamp(-2,0,10),0);assert.equal(clamp(5,0,10),5);assert.equal(clamp(99,0,10),10);});`;writeFileSync(join(source,'clamp.test.mjs'),tests);writeFileSync(join(source,'human-note'),'baseline');git('init','-q');git('config','user.name','Fixture');git('config','user.email','fixture@example.invalid');git('add','.');git('commit','-qm','pilot base');writeFileSync(join(source,'human-note'),'Human pending change to preserve');writeFileSync(join(source,'human-staged'),'Human staged content to preserve');git('add','human-staged');const initialHead=git('rev-parse','HEAD'),initialIndex=git('diff','--cached','--binary');
const check=join(root,'owner-check.mjs');writeFileSync(check,`import assert from 'node:assert/strict';import {pathToFileURL} from 'node:url';import {join} from 'node:path';const {clamp}=await import(pathToFileURL(join(process.cwd(),'clamp.mjs')).href);for(const [v,a,b,expected] of [[-2,0,10,0],[5,0,10,5],[99,0,10,10],[-9,-5,-1,-5],[-3,-5,-1,-3],[0,-5,-1,-1],[3,3,3,3]])assert.equal(clamp(v,a,b),expected);`);const verification=createCompletionCheck({script:check,root:join(root,'proof')});const journal=new TerminalSession({root:state,cwd:source,check:verification.pinned}),view=createStore();const start=Date.now();let calls=0,promptBytes=0;const adapter=new BinaryModelAdapter({binary,project:source,model:'opencode/big-pickle',timeoutMs:90000});const trace:any[]=[];
const model={name:adapter.name,async infer(frame:any,signal?:AbortSignal){calls++;promptBytes+=Buffer.byteLength(JSON.stringify(frame));const at=Date.now();console.log('Inference '+calls+'; goal remains controller-owned');try{const response=await adapter.infer(frame,signal);trace.push({call:calls,elapsed:Date.now()-at,response});writeFileSync(join(root,'trace.json'),JSON.stringify(trace,null,2));return response;}catch(error){trace.push({call:calls,elapsed:Date.now()-at,failure:error instanceof Error?error.message:'unknown'});writeFileSync(join(root,'trace.json'),JSON.stringify(trace,null,2));throw error;}}};
const tools=(cwd:string)=>new ContainerToolRunner({allow:['node','npm','git','rg','ls','cat'],roots:[cwd],defaultCwd:cwd,image,socket,protectedPaths:[state,verification.pinned!.script]});const producer=createProducer({store:view,journal,cwd:source,identities:[],maxSlices:2,model,tools:tools(source),toolsForScope:tools,worktreeRoot:join(state,'workspaces',journal.metadata.id),verification,research:new ResearchTools({root:source}),researchForScope:cwd=>new ResearchTools({root:cwd})});console.log('Pilot artifacts: '+root);
producer.say('Corrige clamp(value,min,max) dans le projet courant : conserver value si dans les bornes, retourner min si inférieur et max si supérieur, y compris bornes négatives ou égales. Préserve les modifications humaines et les tests existants. Prépare un workspace isolé, examine les fichiers, implémente et lance les tests, fais une revue utile, intègre la contribution puis demande finish.');
try{while(view.get().busy)await new Promise(r=>setTimeout(r,200));const session=journal.core.toSession(),report={model:'opencode/big-pickle',root,goalClosed:session.goal?.open===false,integrated:session.events.some(e=>e.subject==='terminal.workspace'&&e.data.phase==='integrated'),sourcePreserved:readFileSync(join(source,'human-note'),'utf8')==='Human pending change to preserve'&&readFileSync(join(source,'human-staged'),'utf8')==='Human staged content to preserve'&&git('rev-parse','HEAD')===initialHead&&git('diff','--cached','--binary')===initialIndex,calls,promptBytes,elapsedMs:Date.now()-start,tokens:null,cost:null,output:readFileSync(join(source,'clamp.mjs'),'utf8'),lastEntries:view.get().entries.slice(-8)};writeFileSync(join(root,'report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));if(!report.goalClosed||!report.integrated||!report.sourcePreserved)process.exitCode=1;}finally{journal.close();}
